// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type EditorService capnp.Client

// EditorService_TypeID is the unique identifier for the type EditorService.
const EditorService_TypeID = 0xd281f133906f9f01

func (c EditorService) Connect(ctx context.Context, params func(EditorService_connect_Params) error) (EditorService_connect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      0,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "connect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_connect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_connect_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) Disconnect(ctx context.Context, params func(EditorService_disconnect_Params) error) (EditorService_disconnect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      1,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "disconnect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_disconnect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_disconnect_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) OpenFile(ctx context.Context, params func(EditorService_openFile_Params) error) (EditorService_openFile_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      2,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "openFile",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_openFile_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_openFile_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) GetUpdates(ctx context.Context, params func(EditorService_getUpdates_Params) error) (EditorService_getUpdates_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      3,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "getUpdates",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 24, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_getUpdates_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_getUpdates_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) ApplyOp(ctx context.Context, params func(EditorService_applyOp_Params) error) (EditorService_applyOp_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      4,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "applyOp",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_applyOp_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_applyOp_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) Save(ctx context.Context, params func(EditorService_save_Params) error) (EditorService_save_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      5,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "save",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_save_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_save_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) CloseBuffer(ctx context.Context, params func(EditorService_closeBuffer_Params) error) (EditorService_closeBuffer_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      6,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "closeBuffer",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_closeBuffer_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_closeBuffer_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) BufferClientCount(ctx context.Context, params func(EditorService_bufferClientCount_Params) error) (EditorService_bufferClientCount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      7,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "bufferClientCount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_bufferClientCount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_bufferClientCount_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c EditorService) String() string {
	return "EditorService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c EditorService) AddRef() EditorService {
	return EditorService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c EditorService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c EditorService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c EditorService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (EditorService) DecodeFromPtr(p capnp.Ptr) EditorService {
	return EditorService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c EditorService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c EditorService) IsSame(other EditorService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c EditorService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c EditorService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A EditorService_Server is a EditorService with a local implementation.
type EditorService_Server interface {
	Connect(context.Context, EditorService_connect) error

	Disconnect(context.Context, EditorService_disconnect) error

	OpenFile(context.Context, EditorService_openFile) error

	GetUpdates(context.Context, EditorService_getUpdates) error

	ApplyOp(context.Context, EditorService_applyOp) error

	Save(context.Context, EditorService_save) error

	CloseBuffer(context.Context, EditorService_closeBuffer) error

	BufferClientCount(context.Context, EditorService_bufferClientCount) error
}

// EditorService_NewServer creates a new Server from an implementation of EditorService_Server.
func EditorService_NewServer(s EditorService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(EditorService_Methods(nil, s), s, c)
}

// EditorService_ServerToClient creates a new Client from an implementation of EditorService_Server.
// The caller is responsible for calling Release on the returned Client.
func EditorService_ServerToClient(s EditorService_Server) EditorService {
	return EditorService(capnp.NewClient(EditorService_NewServer(s)))
}

// EditorService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func EditorService_Methods(methods []server.Method, s EditorService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 8)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      0,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "connect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Connect(ctx, EditorService_connect{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      1,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "disconnect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Disconnect(ctx, EditorService_disconnect{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      2,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "openFile",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.OpenFile(ctx, EditorService_openFile{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      3,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "getUpdates",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetUpdates(ctx, EditorService_getUpdates{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      4,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "applyOp",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ApplyOp(ctx, EditorService_applyOp{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      5,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "save",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Save(ctx, EditorService_save{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      6,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "closeBuffer",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CloseBuffer(ctx, EditorService_closeBuffer{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      7,
			InterfaceName: "internal/proto/editor.capnp:EditorService",
			MethodName:    "bufferClientCount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.BufferClientCount(ctx, EditorService_bufferClientCount{call})
		},
	})

	return methods
}

// EditorService_connect holds the state for a server call to EditorService.connect.
// See server.Call for documentation.
type EditorService_connect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_connect) Args() EditorService_connect_Params {
	return EditorService_connect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_connect) AllocResults() (EditorService_connect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(r), err
}

// EditorService_disconnect holds the state for a server call to EditorService.disconnect.
// See server.Call for documentation.
type EditorService_disconnect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_disconnect) Args() EditorService_disconnect_Params {
	return EditorService_disconnect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_disconnect) AllocResults() (EditorService_disconnect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(r), err
}

// EditorService_openFile holds the state for a server call to EditorService.openFile.
// See server.Call for documentation.
type EditorService_openFile struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_openFile) Args() EditorService_openFile_Params {
	return EditorService_openFile_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_openFile) AllocResults() (EditorService_openFile_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(r), err
}

// EditorService_getUpdates holds the state for a server call to EditorService.getUpdates.
// See server.Call for documentation.
type EditorService_getUpdates struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_getUpdates) Args() EditorService_getUpdates_Params {
	return EditorService_getUpdates_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_getUpdates) AllocResults() (EditorService_getUpdates_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(r), err
}

// EditorService_applyOp holds the state for a server call to EditorService.applyOp.
// See server.Call for documentation.
type EditorService_applyOp struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_applyOp) Args() EditorService_applyOp_Params {
	return EditorService_applyOp_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_applyOp) AllocResults() (EditorService_applyOp_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(r), err
}

// EditorService_save holds the state for a server call to EditorService.save.
// See server.Call for documentation.
type EditorService_save struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_save) Args() EditorService_save_Params {
	return EditorService_save_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_save) AllocResults() (EditorService_save_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(r), err
}

// EditorService_closeBuffer holds the state for a server call to EditorService.closeBuffer.
// See server.Call for documentation.
type EditorService_closeBuffer struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_closeBuffer) Args() EditorService_closeBuffer_Params {
	return EditorService_closeBuffer_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_closeBuffer) AllocResults() (EditorService_closeBuffer_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(r), err
}

// EditorService_bufferClientCount holds the state for a server call to EditorService.bufferClientCount.
// See server.Call for documentation.
type EditorService_bufferClientCount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_bufferClientCount) Args() EditorService_bufferClientCount_Params {
	return EditorService_bufferClientCount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_bufferClientCount) AllocResults() (EditorService_bufferClientCount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(r), err
}

// EditorService_List is a list of EditorService.
type EditorService_List = capnp.CapList[EditorService]

// NewEditorService_List creates a new list of EditorService.
func NewEditorService_List(s *capnp.Segment, sz int32) (EditorService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[EditorService](l), err
}

type EditorService_connect_Params capnp.Struct

// EditorService_connect_Params_TypeID is the unique identifier for the type EditorService_connect_Params.
const EditorService_connect_Params_TypeID = 0xe4418928851d24b2

func NewEditorService_connect_Params(s *capnp.Segment) (EditorService_connect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_connect_Params(st), err
}

func NewRootEditorService_connect_Params(s *capnp.Segment) (EditorService_connect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_connect_Params(st), err
}

func ReadRootEditorService_connect_Params(msg *capnp.Message) (EditorService_connect_Params, error) {
	root, err := msg.Root()
	return EditorService_connect_Params(root.Struct()), err
}

func (s EditorService_connect_Params) String() string {
	str, _ := text.Marshal(0xe4418928851d24b2, capnp.Struct(s))
	return str
}

func (s EditorService_connect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_connect_Params) DecodeFromPtr(p capnp.Ptr) EditorService_connect_Params {
	return EditorService_connect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_connect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_connect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_connect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_connect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_connect_Params_List is a list of EditorService_connect_Params.
type EditorService_connect_Params_List = capnp.StructList[EditorService_connect_Params]

// NewEditorService_connect_Params creates a new list of EditorService_connect_Params.
func NewEditorService_connect_Params_List(s *capnp.Segment, sz int32) (EditorService_connect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_connect_Params](l), err
}

// EditorService_connect_Params_Future is a wrapper for a EditorService_connect_Params promised by a client call.
type EditorService_connect_Params_Future struct{ *capnp.Future }

func (f EditorService_connect_Params_Future) Struct() (EditorService_connect_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_connect_Params(p.Struct()), err
}

type EditorService_connect_Results capnp.Struct

// EditorService_connect_Results_TypeID is the unique identifier for the type EditorService_connect_Results.
const EditorService_connect_Results_TypeID = 0xf837e3273ba4c201

func NewEditorService_connect_Results(s *capnp.Segment) (EditorService_connect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(st), err
}

func NewRootEditorService_connect_Results(s *capnp.Segment) (EditorService_connect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(st), err
}

func ReadRootEditorService_connect_Results(msg *capnp.Message) (EditorService_connect_Results, error) {
	root, err := msg.Root()
	return EditorService_connect_Results(root.Struct()), err
}

func (s EditorService_connect_Results) String() string {
	str, _ := text.Marshal(0xf837e3273ba4c201, capnp.Struct(s))
	return str
}

func (s EditorService_connect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_connect_Results) DecodeFromPtr(p capnp.Ptr) EditorService_connect_Results {
	return EditorService_connect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_connect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_connect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_connect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_connect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_connect_Results) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_connect_Results) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_connect_Results_List is a list of EditorService_connect_Results.
type EditorService_connect_Results_List = capnp.StructList[EditorService_connect_Results]

// NewEditorService_connect_Results creates a new list of EditorService_connect_Results.
func NewEditorService_connect_Results_List(s *capnp.Segment, sz int32) (EditorService_connect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_connect_Results](l), err
}

// EditorService_connect_Results_Future is a wrapper for a EditorService_connect_Results promised by a client call.
type EditorService_connect_Results_Future struct{ *capnp.Future }

func (f EditorService_connect_Results_Future) Struct() (EditorService_connect_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_connect_Results(p.Struct()), err
}

type EditorService_disconnect_Params capnp.Struct

// EditorService_disconnect_Params_TypeID is the unique identifier for the type EditorService_disconnect_Params.
const EditorService_disconnect_Params_TypeID = 0xfdaeb62e8f10b2ff

func NewEditorService_disconnect_Params(s *capnp.Segment) (EditorService_disconnect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_disconnect_Params(st), err
}

func NewRootEditorService_disconnect_Params(s *capnp.Segment) (EditorService_disconnect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_disconnect_Params(st), err
}

func ReadRootEditorService_disconnect_Params(msg *capnp.Message) (EditorService_disconnect_Params, error) {
	root, err := msg.Root()
	return EditorService_disconnect_Params(root.Struct()), err
}

func (s EditorService_disconnect_Params) String() string {
	str, _ := text.Marshal(0xfdaeb62e8f10b2ff, capnp.Struct(s))
	return str
}

func (s EditorService_disconnect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_disconnect_Params) DecodeFromPtr(p capnp.Ptr) EditorService_disconnect_Params {
	return EditorService_disconnect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_disconnect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_disconnect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_disconnect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_disconnect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_disconnect_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_disconnect_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_disconnect_Params_List is a list of EditorService_disconnect_Params.
type EditorService_disconnect_Params_List = capnp.StructList[EditorService_disconnect_Params]

// NewEditorService_disconnect_Params creates a new list of EditorService_disconnect_Params.
func NewEditorService_disconnect_Params_List(s *capnp.Segment, sz int32) (EditorService_disconnect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_disconnect_Params](l), err
}

// EditorService_disconnect_Params_Future is a wrapper for a EditorService_disconnect_Params promised by a client call.
type EditorService_disconnect_Params_Future struct{ *capnp.Future }

func (f EditorService_disconnect_Params_Future) Struct() (EditorService_disconnect_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_disconnect_Params(p.Struct()), err
}

type EditorService_disconnect_Results capnp.Struct

// EditorService_disconnect_Results_TypeID is the unique identifier for the type EditorService_disconnect_Results.
const EditorService_disconnect_Results_TypeID = 0xf3842bc6cf4149eb

func NewEditorService_disconnect_Results(s *capnp.Segment) (EditorService_disconnect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(st), err
}

func NewRootEditorService_disconnect_Results(s *capnp.Segment) (EditorService_disconnect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(st), err
}

func ReadRootEditorService_disconnect_Results(msg *capnp.Message) (EditorService_disconnect_Results, error) {
	root, err := msg.Root()
	return EditorService_disconnect_Results(root.Struct()), err
}

func (s EditorService_disconnect_Results) String() string {
	str, _ := text.Marshal(0xf3842bc6cf4149eb, capnp.Struct(s))
	return str
}

func (s EditorService_disconnect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_disconnect_Results) DecodeFromPtr(p capnp.Ptr) EditorService_disconnect_Results {
	return EditorService_disconnect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_disconnect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_disconnect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_disconnect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_disconnect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_disconnect_Results_List is a list of EditorService_disconnect_Results.
type EditorService_disconnect_Results_List = capnp.StructList[EditorService_disconnect_Results]

// NewEditorService_disconnect_Results creates a new list of EditorService_disconnect_Results.
func NewEditorService_disconnect_Results_List(s *capnp.Segment, sz int32) (EditorService_disconnect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_disconnect_Results](l), err
}

// EditorService_disconnect_Results_Future is a wrapper for a EditorService_disconnect_Results promised by a client call.
type EditorService_disconnect_Results_Future struct{ *capnp.Future }

func (f EditorService_disconnect_Results_Future) Struct() (EditorService_disconnect_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_disconnect_Results(p.Struct()), err
}

type EditorService_openFile_Params capnp.Struct

// EditorService_openFile_Params_TypeID is the unique identifier for the type EditorService_openFile_Params.
const EditorService_openFile_Params_TypeID = 0xcd6d4043f1fd9e2d

func NewEditorService_openFile_Params(s *capnp.Segment) (EditorService_openFile_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_openFile_Params(st), err
}

func NewRootEditorService_openFile_Params(s *capnp.Segment) (EditorService_openFile_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_openFile_Params(st), err
}

func ReadRootEditorService_openFile_Params(msg *capnp.Message) (EditorService_openFile_Params, error) {
	root, err := msg.Root()
	return EditorService_openFile_Params(root.Struct()), err
}

func (s EditorService_openFile_Params) String() string {
	str, _ := text.Marshal(0xcd6d4043f1fd9e2d, capnp.Struct(s))
	return str
}

func (s EditorService_openFile_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_openFile_Params) DecodeFromPtr(p capnp.Ptr) EditorService_openFile_Params {
	return EditorService_openFile_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_openFile_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_openFile_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_openFile_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_openFile_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_openFile_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_openFile_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_openFile_Params) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditorService_openFile_Params) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_openFile_Params) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditorService_openFile_Params) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// EditorService_openFile_Params_List is a list of EditorService_openFile_Params.
type EditorService_openFile_Params_List = capnp.StructList[EditorService_openFile_Params]

// NewEditorService_openFile_Params creates a new list of EditorService_openFile_Params.
func NewEditorService_openFile_Params_List(s *capnp.Segment, sz int32) (EditorService_openFile_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_openFile_Params](l), err
}

// EditorService_openFile_Params_Future is a wrapper for a EditorService_openFile_Params promised by a client call.
type EditorService_openFile_Params_Future struct{ *capnp.Future }

func (f EditorService_openFile_Params_Future) Struct() (EditorService_openFile_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_openFile_Params(p.Struct()), err
}

type EditorService_openFile_Results capnp.Struct

// EditorService_openFile_Results_TypeID is the unique identifier for the type EditorService_openFile_Results.
const EditorService_openFile_Results_TypeID = 0x9881b45d79299b22

func NewEditorService_openFile_Results(s *capnp.Segment) (EditorService_openFile_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(st), err
}

func NewRootEditorService_openFile_Results(s *capnp.Segment) (EditorService_openFile_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(st), err
}

func ReadRootEditorService_openFile_Results(msg *capnp.Message) (EditorService_openFile_Results, error) {
	root, err := msg.Root()
	return EditorService_openFile_Results(root.Struct()), err
}

func (s EditorService_openFile_Results) String() string {
	str, _ := text.Marshal(0x9881b45d79299b22, capnp.Struct(s))
	return str
}

func (s EditorService_openFile_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_openFile_Results) DecodeFromPtr(p capnp.Ptr) EditorService_openFile_Results {
	return EditorService_openFile_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_openFile_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_openFile_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_openFile_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_openFile_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_openFile_Results) BufferId() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_openFile_Results) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s EditorService_openFile_Results) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditorService_openFile_Results) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_openFile_Results) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditorService_openFile_Results) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EditorService_openFile_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EditorService_openFile_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// EditorService_openFile_Results_List is a list of EditorService_openFile_Results.
type EditorService_openFile_Results_List = capnp.StructList[EditorService_openFile_Results]

// NewEditorService_openFile_Results creates a new list of EditorService_openFile_Results.
func NewEditorService_openFile_Results_List(s *capnp.Segment, sz int32) (EditorService_openFile_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_openFile_Results](l), err
}

// EditorService_openFile_Results_Future is a wrapper for a EditorService_openFile_Results promised by a client call.
type EditorService_openFile_Results_Future struct{ *capnp.Future }

func (f EditorService_openFile_Results_Future) Struct() (EditorService_openFile_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_openFile_Results(p.Struct()), err
}

type EditorService_getUpdates_Params capnp.Struct

// EditorService_getUpdates_Params_TypeID is the unique identifier for the type EditorService_getUpdates_Params.
const EditorService_getUpdates_Params_TypeID = 0xb3c8a09d8d7f2391

func NewEditorService_getUpdates_Params(s *capnp.Segment) (EditorService_getUpdates_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EditorService_getUpdates_Params(st), err
}

func NewRootEditorService_getUpdates_Params(s *capnp.Segment) (EditorService_getUpdates_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EditorService_getUpdates_Params(st), err
}

func ReadRootEditorService_getUpdates_Params(msg *capnp.Message) (EditorService_getUpdates_Params, error) {
	root, err := msg.Root()
	return EditorService_getUpdates_Params(root.Struct()), err
}

func (s EditorService_getUpdates_Params) String() string {
	str, _ := text.Marshal(0xb3c8a09d8d7f2391, capnp.Struct(s))
	return str
}

func (s EditorService_getUpdates_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_getUpdates_Params) DecodeFromPtr(p capnp.Ptr) EditorService_getUpdates_Params {
	return EditorService_getUpdates_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_getUpdates_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_getUpdates_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_getUpdates_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_getUpdates_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_getUpdates_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_getUpdates_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_getUpdates_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_getUpdates_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s EditorService_getUpdates_Params) SinceVersion() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EditorService_getUpdates_Params) SetSinceVersion(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// EditorService_getUpdates_Params_List is a list of EditorService_getUpdates_Params.
type EditorService_getUpdates_Params_List = capnp.StructList[EditorService_getUpdates_Params]

// NewEditorService_getUpdates_Params creates a new list of EditorService_getUpdates_Params.
func NewEditorService_getUpdates_Params_List(s *capnp.Segment, sz int32) (EditorService_getUpdates_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_getUpdates_Params](l), err
}

// EditorService_getUpdates_Params_Future is a wrapper for a EditorService_getUpdates_Params promised by a client call.
type EditorService_getUpdates_Params_Future struct{ *capnp.Future }

func (f EditorService_getUpdates_Params_Future) Struct() (EditorService_getUpdates_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_getUpdates_Params(p.Struct()), err
}

type EditorService_getUpdates_Results capnp.Struct

// EditorService_getUpdates_Results_TypeID is the unique identifier for the type EditorService_getUpdates_Results.
const EditorService_getUpdates_Results_TypeID = 0xdc19fdc1e173fe90

func NewEditorService_getUpdates_Results(s *capnp.Segment) (EditorService_getUpdates_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(st), err
}

func NewRootEditorService_getUpdates_Results(s *capnp.Segment) (EditorService_getUpdates_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(st), err
}

func ReadRootEditorService_getUpdates_Results(msg *capnp.Message) (EditorService_getUpdates_Results, error) {
	root, err := msg.Root()
	return EditorService_getUpdates_Results(root.Struct()), err
}

func (s EditorService_getUpdates_Results) String() string {
	str, _ := text.Marshal(0xdc19fdc1e173fe90, capnp.Struct(s))
	return str
}

func (s EditorService_getUpdates_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_getUpdates_Results) DecodeFromPtr(p capnp.Ptr) EditorService_getUpdates_Results {
	return EditorService_getUpdates_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_getUpdates_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_getUpdates_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_getUpdates_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_getUpdates_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_getUpdates_Results) Ops() (EditOp_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EditOp_List(p.List()), err
}

func (s EditorService_getUpdates_Results) HasOps() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_getUpdates_Results) SetOps(v EditOp_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewOps sets the ops field to a newly
// allocated EditOp_List, preferring placement in s's segment.
func (s EditorService_getUpdates_Results) NewOps(n int32) (EditOp_List, error) {
	l, err := NewEditOp_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return EditOp_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s EditorService_getUpdates_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_getUpdates_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_getUpdates_Results_List is a list of EditorService_getUpdates_Results.
type EditorService_getUpdates_Results_List = capnp.StructList[EditorService_getUpdates_Results]

// NewEditorService_getUpdates_Results creates a new list of EditorService_getUpdates_Results.
func NewEditorService_getUpdates_Results_List(s *capnp.Segment, sz int32) (EditorService_getUpdates_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_getUpdates_Results](l), err
}

// EditorService_getUpdates_Results_Future is a wrapper for a EditorService_getUpdates_Results promised by a client call.
type EditorService_getUpdates_Results_Future struct{ *capnp.Future }

func (f EditorService_getUpdates_Results_Future) Struct() (EditorService_getUpdates_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_getUpdates_Results(p.Struct()), err
}

type EditorService_applyOp_Params capnp.Struct

// EditorService_applyOp_Params_TypeID is the unique identifier for the type EditorService_applyOp_Params.
const EditorService_applyOp_Params_TypeID = 0x81f9af23ee6aa27e

func NewEditorService_applyOp_Params(s *capnp.Segment) (EditorService_applyOp_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_applyOp_Params(st), err
}

func NewRootEditorService_applyOp_Params(s *capnp.Segment) (EditorService_applyOp_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_applyOp_Params(st), err
}

func ReadRootEditorService_applyOp_Params(msg *capnp.Message) (EditorService_applyOp_Params, error) {
	root, err := msg.Root()
	return EditorService_applyOp_Params(root.Struct()), err
}

func (s EditorService_applyOp_Params) String() string {
	str, _ := text.Marshal(0x81f9af23ee6aa27e, capnp.Struct(s))
	return str
}

func (s EditorService_applyOp_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_applyOp_Params) DecodeFromPtr(p capnp.Ptr) EditorService_applyOp_Params {
	return EditorService_applyOp_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_applyOp_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_applyOp_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_applyOp_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_applyOp_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_applyOp_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_applyOp_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_applyOp_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_applyOp_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s EditorService_applyOp_Params) Op() (EditOp, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EditOp(p.Struct()), err
}

func (s EditorService_applyOp_Params) HasOp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_applyOp_Params) SetOp(v EditOp) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewOp sets the op field to a newly
// allocated EditOp struct, preferring placement in s's segment.
func (s EditorService_applyOp_Params) NewOp() (EditOp, error) {
	ss, err := NewEditOp(capnp.Struct(s).Segment())
	if err != nil {
		return EditOp{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EditorService_applyOp_Params_List is a list of EditorService_applyOp_Params.
type EditorService_applyOp_Params_List = capnp.StructList[EditorService_applyOp_Params]

// NewEditorService_applyOp_Params creates a new list of EditorService_applyOp_Params.
func NewEditorService_applyOp_Params_List(s *capnp.Segment, sz int32) (EditorService_applyOp_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_applyOp_Params](l), err
}

// EditorService_applyOp_Params_Future is a wrapper for a EditorService_applyOp_Params promised by a client call.
type EditorService_applyOp_Params_Future struct{ *capnp.Future }

func (f EditorService_applyOp_Params_Future) Struct() (EditorService_applyOp_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_applyOp_Params(p.Struct()), err
}
func (p EditorService_applyOp_Params_Future) Op() EditOp_Future {
	return EditOp_Future{Future: p.Future.Field(0, nil)}
}

type EditorService_applyOp_Results capnp.Struct

// EditorService_applyOp_Results_TypeID is the unique identifier for the type EditorService_applyOp_Results.
const EditorService_applyOp_Results_TypeID = 0xbef0f62b1a5ccab5

func NewEditorService_applyOp_Results(s *capnp.Segment) (EditorService_applyOp_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(st), err
}

func NewRootEditorService_applyOp_Results(s *capnp.Segment) (EditorService_applyOp_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(st), err
}

func ReadRootEditorService_applyOp_Results(msg *capnp.Message) (EditorService_applyOp_Results, error) {
	root, err := msg.Root()
	return EditorService_applyOp_Results(root.Struct()), err
}

func (s EditorService_applyOp_Results) String() string {
	str, _ := text.Marshal(0xbef0f62b1a5ccab5, capnp.Struct(s))
	return str
}

func (s EditorService_applyOp_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_applyOp_Results) DecodeFromPtr(p capnp.Ptr) EditorService_applyOp_Results {
	return EditorService_applyOp_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_applyOp_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_applyOp_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_applyOp_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_applyOp_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_applyOp_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_applyOp_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_applyOp_Results_List is a list of EditorService_applyOp_Results.
type EditorService_applyOp_Results_List = capnp.StructList[EditorService_applyOp_Results]

// NewEditorService_applyOp_Results creates a new list of EditorService_applyOp_Results.
func NewEditorService_applyOp_Results_List(s *capnp.Segment, sz int32) (EditorService_applyOp_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_applyOp_Results](l), err
}

// EditorService_applyOp_Results_Future is a wrapper for a EditorService_applyOp_Results promised by a client call.
type EditorService_applyOp_Results_Future struct{ *capnp.Future }

func (f EditorService_applyOp_Results_Future) Struct() (EditorService_applyOp_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_applyOp_Results(p.Struct()), err
}

type EditorService_save_Params capnp.Struct

// EditorService_save_Params_TypeID is the unique identifier for the type EditorService_save_Params.
const EditorService_save_Params_TypeID = 0xdd178a12d938882b

func NewEditorService_save_Params(s *capnp.Segment) (EditorService_save_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_save_Params(st), err
}

func NewRootEditorService_save_Params(s *capnp.Segment) (EditorService_save_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_save_Params(st), err
}

func ReadRootEditorService_save_Params(msg *capnp.Message) (EditorService_save_Params, error) {
	root, err := msg.Root()
	return EditorService_save_Params(root.Struct()), err
}

func (s EditorService_save_Params) String() string {
	str, _ := text.Marshal(0xdd178a12d938882b, capnp.Struct(s))
	return str
}

func (s EditorService_save_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_save_Params) DecodeFromPtr(p capnp.Ptr) EditorService_save_Params {
	return EditorService_save_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_save_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_save_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_save_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_save_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_save_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_save_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_save_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_save_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// EditorService_save_Params_List is a list of EditorService_save_Params.
type EditorService_save_Params_List = capnp.StructList[EditorService_save_Params]

// NewEditorService_save_Params creates a new list of EditorService_save_Params.
func NewEditorService_save_Params_List(s *capnp.Segment, sz int32) (EditorService_save_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_save_Params](l), err
}

// EditorService_save_Params_Future is a wrapper for a EditorService_save_Params promised by a client call.
type EditorService_save_Params_Future struct{ *capnp.Future }

func (f EditorService_save_Params_Future) Struct() (EditorService_save_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_save_Params(p.Struct()), err
}

type EditorService_save_Results capnp.Struct

// EditorService_save_Results_TypeID is the unique identifier for the type EditorService_save_Results.
const EditorService_save_Results_TypeID = 0x8089f48db0346b82

func NewEditorService_save_Results(s *capnp.Segment) (EditorService_save_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(st), err
}

func NewRootEditorService_save_Results(s *capnp.Segment) (EditorService_save_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(st), err
}

func ReadRootEditorService_save_Results(msg *capnp.Message) (EditorService_save_Results, error) {
	root, err := msg.Root()
	return EditorService_save_Results(root.Struct()), err
}

func (s EditorService_save_Results) String() string {
	str, _ := text.Marshal(0x8089f48db0346b82, capnp.Struct(s))
	return str
}

func (s EditorService_save_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_save_Results) DecodeFromPtr(p capnp.Ptr) EditorService_save_Results {
	return EditorService_save_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_save_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_save_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_save_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_save_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_save_Results_List is a list of EditorService_save_Results.
type EditorService_save_Results_List = capnp.StructList[EditorService_save_Results]

// NewEditorService_save_Results creates a new list of EditorService_save_Results.
func NewEditorService_save_Results_List(s *capnp.Segment, sz int32) (EditorService_save_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_save_Results](l), err
}

// EditorService_save_Results_Future is a wrapper for a EditorService_save_Results promised by a client call.
type EditorService_save_Results_Future struct{ *capnp.Future }

func (f EditorService_save_Results_Future) Struct() (EditorService_save_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_save_Results(p.Struct()), err
}

type EditorService_closeBuffer_Params capnp.Struct

// EditorService_closeBuffer_Params_TypeID is the unique identifier for the type EditorService_closeBuffer_Params.
const EditorService_closeBuffer_Params_TypeID = 0xca42a841ee65eea6

func NewEditorService_closeBuffer_Params(s *capnp.Segment) (EditorService_closeBuffer_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_closeBuffer_Params(st), err
}

func NewRootEditorService_closeBuffer_Params(s *capnp.Segment) (EditorService_closeBuffer_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_closeBuffer_Params(st), err
}

func ReadRootEditorService_closeBuffer_Params(msg *capnp.Message) (EditorService_closeBuffer_Params, error) {
	root, err := msg.Root()
	return EditorService_closeBuffer_Params(root.Struct()), err
}

func (s EditorService_closeBuffer_Params) String() string {
	str, _ := text.Marshal(0xca42a841ee65eea6, capnp.Struct(s))
	return str
}

func (s EditorService_closeBuffer_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_closeBuffer_Params) DecodeFromPtr(p capnp.Ptr) EditorService_closeBuffer_Params {
	return EditorService_closeBuffer_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_closeBuffer_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_closeBuffer_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_closeBuffer_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_closeBuffer_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_closeBuffer_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_closeBuffer_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_closeBuffer_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_closeBuffer_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// EditorService_closeBuffer_Params_List is a list of EditorService_closeBuffer_Params.
type EditorService_closeBuffer_Params_List = capnp.StructList[EditorService_closeBuffer_Params]

// NewEditorService_closeBuffer_Params creates a new list of EditorService_closeBuffer_Params.
func NewEditorService_closeBuffer_Params_List(s *capnp.Segment, sz int32) (EditorService_closeBuffer_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_closeBuffer_Params](l), err
}

// EditorService_closeBuffer_Params_Future is a wrapper for a EditorService_closeBuffer_Params promised by a client call.
type EditorService_closeBuffer_Params_Future struct{ *capnp.Future }

func (f EditorService_closeBuffer_Params_Future) Struct() (EditorService_closeBuffer_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_closeBuffer_Params(p.Struct()), err
}

type EditorService_closeBuffer_Results capnp.Struct

// EditorService_closeBuffer_Results_TypeID is the unique identifier for the type EditorService_closeBuffer_Results.
const EditorService_closeBuffer_Results_TypeID = 0xbc963afed2baaec8

func NewEditorService_closeBuffer_Results(s *capnp.Segment) (EditorService_closeBuffer_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(st), err
}

func NewRootEditorService_closeBuffer_Results(s *capnp.Segment) (EditorService_closeBuffer_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(st), err
}

func ReadRootEditorService_closeBuffer_Results(msg *capnp.Message) (EditorService_closeBuffer_Results, error) {
	root, err := msg.Root()
	return EditorService_closeBuffer_Results(root.Struct()), err
}

func (s EditorService_closeBuffer_Results) String() string {
	str, _ := text.Marshal(0xbc963afed2baaec8, capnp.Struct(s))
	return str
}

func (s EditorService_closeBuffer_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_closeBuffer_Results) DecodeFromPtr(p capnp.Ptr) EditorService_closeBuffer_Results {
	return EditorService_closeBuffer_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_closeBuffer_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_closeBuffer_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_closeBuffer_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_closeBuffer_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_closeBuffer_Results_List is a list of EditorService_closeBuffer_Results.
type EditorService_closeBuffer_Results_List = capnp.StructList[EditorService_closeBuffer_Results]

// NewEditorService_closeBuffer_Results creates a new list of EditorService_closeBuffer_Results.
func NewEditorService_closeBuffer_Results_List(s *capnp.Segment, sz int32) (EditorService_closeBuffer_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_closeBuffer_Results](l), err
}

// EditorService_closeBuffer_Results_Future is a wrapper for a EditorService_closeBuffer_Results promised by a client call.
type EditorService_closeBuffer_Results_Future struct{ *capnp.Future }

func (f EditorService_closeBuffer_Results_Future) Struct() (EditorService_closeBuffer_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_closeBuffer_Results(p.Struct()), err
}

type EditorService_bufferClientCount_Params capnp.Struct

// EditorService_bufferClientCount_Params_TypeID is the unique identifier for the type EditorService_bufferClientCount_Params.
const EditorService_bufferClientCount_Params_TypeID = 0xe8abb7e7f38eda68

func NewEditorService_bufferClientCount_Params(s *capnp.Segment) (EditorService_bufferClientCount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Params(st), err
}

func NewRootEditorService_bufferClientCount_Params(s *capnp.Segment) (EditorService_bufferClientCount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Params(st), err
}

func ReadRootEditorService_bufferClientCount_Params(msg *capnp.Message) (EditorService_bufferClientCount_Params, error) {
	root, err := msg.Root()
	return EditorService_bufferClientCount_Params(root.Struct()), err
}

func (s EditorService_bufferClientCount_Params) String() string {
	str, _ := text.Marshal(0xe8abb7e7f38eda68, capnp.Struct(s))
	return str
}

func (s EditorService_bufferClientCount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_bufferClientCount_Params) DecodeFromPtr(p capnp.Ptr) EditorService_bufferClientCount_Params {
	return EditorService_bufferClientCount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_bufferClientCount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_bufferClientCount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_bufferClientCount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_bufferClientCount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_bufferClientCount_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_bufferClientCount_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// EditorService_bufferClientCount_Params_List is a list of EditorService_bufferClientCount_Params.
type EditorService_bufferClientCount_Params_List = capnp.StructList[EditorService_bufferClientCount_Params]

// NewEditorService_bufferClientCount_Params creates a new list of EditorService_bufferClientCount_Params.
func NewEditorService_bufferClientCount_Params_List(s *capnp.Segment, sz int32) (EditorService_bufferClientCount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_bufferClientCount_Params](l), err
}

// EditorService_bufferClientCount_Params_Future is a wrapper for a EditorService_bufferClientCount_Params promised by a client call.
type EditorService_bufferClientCount_Params_Future struct{ *capnp.Future }

func (f EditorService_bufferClientCount_Params_Future) Struct() (EditorService_bufferClientCount_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_bufferClientCount_Params(p.Struct()), err
}

type EditorService_bufferClientCount_Results capnp.Struct

// EditorService_bufferClientCount_Results_TypeID is the unique identifier for the type EditorService_bufferClientCount_Results.
const EditorService_bufferClientCount_Results_TypeID = 0xcdecfd1a01f89461

func NewEditorService_bufferClientCount_Results(s *capnp.Segment) (EditorService_bufferClientCount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(st), err
}

func NewRootEditorService_bufferClientCount_Results(s *capnp.Segment) (EditorService_bufferClientCount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(st), err
}

func ReadRootEditorService_bufferClientCount_Results(msg *capnp.Message) (EditorService_bufferClientCount_Results, error) {
	root, err := msg.Root()
	return EditorService_bufferClientCount_Results(root.Struct()), err
}

func (s EditorService_bufferClientCount_Results) String() string {
	str, _ := text.Marshal(0xcdecfd1a01f89461, capnp.Struct(s))
	return str
}

func (s EditorService_bufferClientCount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_bufferClientCount_Results) DecodeFromPtr(p capnp.Ptr) EditorService_bufferClientCount_Results {
	return EditorService_bufferClientCount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_bufferClientCount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_bufferClientCount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_bufferClientCount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_bufferClientCount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_bufferClientCount_Results) Count() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_bufferClientCount_Results) SetCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// EditorService_bufferClientCount_Results_List is a list of EditorService_bufferClientCount_Results.
type EditorService_bufferClientCount_Results_List = capnp.StructList[EditorService_bufferClientCount_Results]

// NewEditorService_bufferClientCount_Results creates a new list of EditorService_bufferClientCount_Results.
func NewEditorService_bufferClientCount_Results_List(s *capnp.Segment, sz int32) (EditorService_bufferClientCount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_bufferClientCount_Results](l), err
}

// EditorService_bufferClientCount_Results_Future is a wrapper for a EditorService_bufferClientCount_Results promised by a client call.
type EditorService_bufferClientCount_Results_Future struct{ *capnp.Future }

func (f EditorService_bufferClientCount_Results_Future) Struct() (EditorService_bufferClientCount_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_bufferClientCount_Results(p.Struct()), err
}

type EditOp capnp.Struct

// EditOp_TypeID is the unique identifier for the type EditOp.
const EditOp_TypeID = 0x9204a190c081b3a5

func NewEditOp(s *capnp.Segment) (EditOp, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1})
	return EditOp(st), err
}

func NewRootEditOp(s *capnp.Segment) (EditOp, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1})
	return EditOp(st), err
}

func ReadRootEditOp(msg *capnp.Message) (EditOp, error) {
	root, err := msg.Root()
	return EditOp(root.Struct()), err
}

func (s EditOp) String() string {
	str, _ := text.Marshal(0x9204a190c081b3a5, capnp.Struct(s))
	return str
}

func (s EditOp) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditOp) DecodeFromPtr(p capnp.Ptr) EditOp {
	return EditOp(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditOp) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditOp) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditOp) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditOp) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditOp) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditOp) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditOp) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EditOp) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EditOp) Type() EditOp_OpType {
	return EditOp_OpType(capnp.Struct(s).Uint16(16))
}

func (s EditOp) SetType(v EditOp_OpType) {
	capnp.Struct(s).SetUint16(16, uint16(v))
}

func (s EditOp) InsertLine() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s EditOp) SetInsertLine(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s EditOp) InsertCol() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s EditOp) SetInsertCol(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

func (s EditOp) InsertText() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditOp) HasInsertText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditOp) InsertTextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditOp) SetInsertText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EditOp) FromLine() uint32 {
	return capnp.Struct(s).Uint32(28)
}

func (s EditOp) SetFromLine(v uint32) {
	capnp.Struct(s).SetUint32(28, v)
}

func (s EditOp) FromCol() uint32 {
	return capnp.Struct(s).Uint32(32)
}

func (s EditOp) SetFromCol(v uint32) {
	capnp.Struct(s).SetUint32(32, v)
}

func (s EditOp) ToLine() uint32 {
	return capnp.Struct(s).Uint32(36)
}

func (s EditOp) SetToLine(v uint32) {
	capnp.Struct(s).SetUint32(36, v)
}

func (s EditOp) ToCol() uint32 {
	return capnp.Struct(s).Uint32(40)
}

func (s EditOp) SetToCol(v uint32) {
	capnp.Struct(s).SetUint32(40, v)
}

// EditOp_List is a list of EditOp.
type EditOp_List = capnp.StructList[EditOp]

// NewEditOp creates a new list of EditOp.
func NewEditOp_List(s *capnp.Segment, sz int32) (EditOp_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1}, sz)
	return capnp.StructList[EditOp](l), err
}

// EditOp_Future is a wrapper for a EditOp promised by a client call.
type EditOp_Future struct{ *capnp.Future }

func (f EditOp_Future) Struct() (EditOp, error) {
	p, err := f.Future.Ptr()
	return EditOp(p.Struct()), err
}

type EditOp_OpType uint16

// EditOp_OpType_TypeID is the unique identifier for the type EditOp_OpType.
const EditOp_OpType_TypeID = 0xce808f7bfdbadb18

// Values of EditOp_OpType.
const (
	EditOp_OpType_noop   EditOp_OpType = 0
	EditOp_OpType_insert EditOp_OpType = 1
	EditOp_OpType_delete EditOp_OpType = 2
)

// String returns the enum's constant name.
func (c EditOp_OpType) String() string {
	switch c {
	case EditOp_OpType_noop:
		return "noop"
	case EditOp_OpType_insert:
		return "insert"
	case EditOp_OpType_delete:
		return "delete"

	default:
		return ""
	}
}

// EditOp_OpTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EditOp_OpTypeFromString(c string) EditOp_OpType {
	switch c {
	case "noop":
		return EditOp_OpType_noop
	case "insert":
		return EditOp_OpType_insert
	case "delete":
		return EditOp_OpType_delete

	default:
		return 0
	}
}

type EditOp_OpType_List = capnp.EnumList[EditOp_OpType]

func NewEditOp_OpType_List(s *capnp.Segment, sz int32) (EditOp_OpType_List, error) {
	return capnp.NewEnumList[EditOp_OpType](s, sz)
}

const schema_d75b3b54eb3ed6a2 = "x\xda\xccVol\x14e\x13\x9f\xd9g\xef\xf6\xee\xed" +
	"\xc1u\xdf=Bi \xe5\x85\xbey\xdb\x02\x85\xd2\xbe" +
	"\xa1\x16\xf0\xae-\x18h \xbd\xed\x15#\x88\x89\xc7\xf5" +
	"\xa9\x1c^o7\xb7[\xb41Zj$\x11\x13\x84\x12" +
	"c$\x06\x15\xa2Fc\x00\x01\xff$D\x8d\x98hH" +
	"\x134\x90\xa8\x01\xe5\x03\xfe\x89\x0a\x06\xad\x18\x03\x1f\xca" +
	"\x9a\xd9\xbb\xdd\xdbb+\xb4|\xf1\xe3\xfev\x9ey~" +
	"3\xf3\x9byf\x11\x13cb\xdd\x94_$\x10\xd4\x8d" +
	">\xbf\xf5\xf8\x83\x0do\xee\xfc}\xc76\x90k\x10@" +
	"\x94\x00\xea\xcf\xb3\xe3\x08\xa2\xf5\xd8\x81-\x97\xe7\x1e\xbe" +
	"6\x00j\x0d\x0a\x00>\xa4\x7f\xa7\xd8\x10\x02*\x17\xd8" +
	"a@\xeb\x95c\x03\x1f\xee\xde/\xee\x01u&\xfa\xad" +
	"\x03_\xdcy\xa9s\xe9\xbd_\x16,\x07\xc4rT\x06" +
	"\xc5\xe9\x00\xf5{\xc5%\x02\xa05\xe7\xf9\xea\xbe\xfb\xde" +
	"\x1axn\x94\xc3\x9f\xfc\xe7\xc8\xe1\x88\x9f\x1c\x0e\xce\xed" +
	"\xdf\xb9\xef\xa5\x93\xc7\xc8\x82\x15\xd8\xec\x95\xbe!\x83\x83" +
	"\x12\x19\x9c<t\xfc\xcc\xf5\xa6g\xdf\xf3\xb0U\x03\xbf" +
	"\x11\xdb\xb7\x876\x96\xcf\xfb\xe3\xd7\x0f\xe8\xa8\xf3ke" +
	"\xe0\x0c\x1d]\x1f\x88\x02Z\xaf^\xe6\x97\x9b_k\x19" +
	"*\xdcn\x1b\xf4\x05.\x92\xc1\xce\xc0C\x80\xd6\x82\x17" +
	"F\x86[c=\xa7\x0a\x1e\xf2\xf4\x86\xf3.|A\xb2" +
	"H>s\x15\xcbG~>\xe5\xbd\x83\x07\xe7\x08\x80\xca" +
	"\xa3A\xba\xa3\xec\xab\xe3#\x8f\xec\xda\xf6)\xc8s\x85" +
	"bv\x00\xeb\xf7\x05;P9\x12\x94\x00\x94\x83\xc1v" +
	"@\x0b_\xd4v\xd7\x0f\x0f\x9c\x01y&+f\x0e\xb0" +
	"\xfe\x04Y~N\x96\xf5\xa7\x83\x92\xa0T\x97H\x00\xd6" +
	"\xee\xeb\xc6\x85\x13#3\xbe\x1e\xc5M.\xb1\xd9\xff\xb7" +
	"\x84\xb8\xcd{\xb2\xf1\xec\xbf\x9f\x9a~\xde\x1b\xde`\xc9" +
	"Q2\xd8o\x1b\x1c\xad\x9c\xb5\xbdjG\xf3w\x9e\xd4" +
	"\xf9BC\x94\xba\xcd\xe7\x9e\xbe\xf2\xc3\xbbo\xfc\xe8\x0d" +
	"\xebZI9\x85%\x87(\xacK\xab\x9b?\xfbd\xde" +
	"\x13W<G\xff\x1f\xbaHG\xf1\xa3\x97\x97\xfe\xef\xdb" +
	"%W\xbdG\xabCv\xca\x96\xdbG\xad\xa3\xa5\xbbj" +
	"\xdf94\xe25H\x86\xec\x8a\xf6\x86\xa2\xb0\xc0Jg" +
	"M\x9e\xcb&3\xbe\x85zN3\xb5\x85\xbc+mj" +
	"\xb9\xdaTR\xcf\xeaM+\xed\x8f\x04\xcfmM\xa7x" +
	"\xad\x91\xdc\xca+;\xa2\xdc\xe8\xcd\x98\x86{\xd0\x7f\xf3" +
	"\x83I]\xcf\xf4\xb5\xeb\x95\xf1d.\xd9c\x00\xa8!" +
	"&\x02\x88\x08 \xafl\x03PW0T\xe3\x02\xca(" +
	"D\x88\xa4\xbc\x96\xc05\x0c\xd5{\x04$L\x00\x90\xd7" +
	"\x95\x03\xa8q\x86\xeaF\x01\xadT&\xcd\xb3\xe6\xea." +
	"\x00\xc0 \x08\x18\x04\xb46\xf5vw\xf3\\\x1e\x0b\x80" +
	"\x80\x01@\xa6\xe9X\xea\xd5\x01\x96\x02\xba\xc4\xd9x\xc4" +
	"Y\xbb\xae\x8a\xe8U\x136E\xdb\xf5\xce>\x9d\xabU" +
	"\x0es%\x88m\x00\x89\x002LD\x90\xc8\xa3M^" +
	"\x91\xb1\x05 \x11\"\xbc\x8cp!`\x07\xa0L\xc3\x1a" +
	"\x80D)\xe13\x09g\xbe\x08\xf5\x982\x037\x00$" +
	"\xca\x08\xaf$\\\xf4GP\x04P\xfe\x83\x1d\x00\x89\xd9" +
	"\x84\xcfG\x01\xd1\x17A\x1f\x80Rm\x9bW\x11\xdc@" +
	"\xe6~)\x82~\x00\xa5\xce\xa6\xb3\x88\xf0e\x84K\x81" +
	"\x08\x89T\xb9\xc3\xa6\xd3@x\x8c\xf0@0\x82\x01\x00" +
	"e96\x01$\x1a\x09_Ax\xf0_\x11\x0c\x02(" +
	"\xcd\xb8\x18 \xb1\x8c\xf0U8v\xaa\xfb\xb7\xf2\x9c\x91" +
	"\xd6\xb2\xcew\xd8\xec\xd39\x86\x8b\xf9\x02\xc4\xb0\x9dh" +
	"\x83\xe7\xcc5i`Y\xee\x94\xa4\x00\xb6j\x80\x99\x1b" +
	"\xb0N\x0e\xeca\x13C `\x08\xd0\xea\xcei=k" +
	"\xd2Y\xee\xa9g?a\xad\x9a{0jjd\xe1|" +
	"V\x98\x9a\xe7\xe7D\x04\xaa\xe9<{W:\xc3+;" +
	"H\xdc\xcc4\xc6Qh\xa1\xc6\xf2\xda\x16\x00u\x15C" +
	"\xb5\x93\x0a\x8cy\x85\xaa-E\xd5\x8e\xa5\xc6\xfe\x94\x96" +
	"5y\xd6\x8d\xf0\xc64N\x84\xf0\x03\xdc\\\xa7w%" +
	"MnPSI\xc9\x1ec\"=%\x0bNSm\x01" +
	"P;\x19\xaa\xf7\xdfzSYF:\x9b\xe2w\xf3\x1c" +
	"\x84'\xcb>\x95\xd1\x0c\xdeb\xbb\xae\xec\xe0\x15\x93\x9e" +
	"'v\xb5L4T\xd1\x8d}\x0a\x15!\xc0P\x8d\x08" +
	"\xb7\x95`/\xc5x2LsK\x0d\xb8\xb7TS2" +
	"\xab\x18\xaa\x0d\x9e\x0c\xd7\x11\xb8\x88\xa1\xbal\x02\xc9\x9c" +
	"\x8cH\xed1\x8a\xe3\xf1q4ZW\x03\xa0\xceg\xa8" +
	"6\x8eM'\xac'\xcd\xcdn\xb79<\xa4\x9b\xf3\xc8" +
	"\x87\xd1j{l\xd5z\xb3\xa6]\x07)c\x8e\xaa\xc3" +
	"\xe2b\x1d*Rd\xf5\x97\x90\xc5\xf1\xaej\xd7k\xed" +
	"i\x8b<\x8e\xa8\x86l\xa5\xce\xaa\xa1\xa9\"Ok\x02" +
	"@A\x9e\xd2\x04\x10\xcej\x9a\x1e\xcd\x8f\x8eh\x17\xcf" +
	"p\x93\xdf\xdc\xb5\x13E\xde\xf5l\xe6\x03p\x1fft" +
	"\x1eSy\xb8\x05\x04\xf9{\x09\x8b\xcf':O\xb0|" +
	"v\x03\x08\xf2i\x09\x05w_Ag\xaf\x92?n\x03" +
	"A~_B\xe6.R\xe8,\x0e\xf2\x11:\xf7\xba\x84" +
	"\xc5\xbd\x0e\x9d\x95I\xdeG\xf7\x0dJ\xe8s\xb7\x08t" +
	"\xd6By{\x0d\x08r\x9f\x84~w\x81Bg\x09\x93" +
	"{6\x81 s\x09%w\x85@gE\x92\xd7\xef\x01" +
	"A^'\xd1\xd0\xc9\xf2\x94\x19C\xab+m\xd8\x1f\xc0" +
	"\xecOGN\x00\x10C\xcb\x19(\xc0\xb8\x11\xc3\xfeB" +
	"\x87\xc50L\x8f~\x8c\x04\x94\xef\x07\x90\xbay.\xe6" +
	"h\xb95\x83\x8e\x0a\xd0\x8ca\x1c';\xc4:\xb8\x11" +
	"\xa6)\xe0\xd5\xf4\x1c\x00\xb5\x92\xa1\x1a+jz9u" +
	"w#Cu\x85\x80\x92\xa6\x1b8\x150\xce\xf0\x86G" +
	"~\xea\xdf\xcc\xd6[]s\xe2\x15\xc9\x7fB\xcf\x17\xaa" +
	"\xe7nN\xb7\xd7\xa7\xe4\x85\xf5\x8cj\xd36{\x1bC" +
	"\xb5L\xb8m\xae\x8e\xbeR\xa6[\xce\xc9\x84:\xd6P" +
	"\xf7\xb2\x1c+\xcb\x93c\xe9\xbc\x9c\xb7~\xd1\x9f\x01\x00" +
	"\x00\xff\xffwJ\xbf\xa1"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d75b3b54eb3ed6a2,
		Nodes: []uint64{
			0x8089f48db0346b82,
			0x81f9af23ee6aa27e,
			0x9204a190c081b3a5,
			0x9881b45d79299b22,
			0xb3c8a09d8d7f2391,
			0xbc963afed2baaec8,
			0xbef0f62b1a5ccab5,
			0xca42a841ee65eea6,
			0xcd6d4043f1fd9e2d,
			0xcdecfd1a01f89461,
			0xce808f7bfdbadb18,
			0xd281f133906f9f01,
			0xdc19fdc1e173fe90,
			0xdd178a12d938882b,
			0xe4418928851d24b2,
			0xe8abb7e7f38eda68,
			0xf3842bc6cf4149eb,
			0xf837e3273ba4c201,
			0xfdaeb62e8f10b2ff,
		},
		Compressed: true,
	})
}
