// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type EditorService capnp.Client

// EditorService_TypeID is the unique identifier for the type EditorService.
const EditorService_TypeID = 0xd281f133906f9f01

func (c EditorService) Connect(ctx context.Context, params func(EditorService_connect_Params) error) (EditorService_connect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      0,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "connect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_connect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_connect_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) Disconnect(ctx context.Context, params func(EditorService_disconnect_Params) error) (EditorService_disconnect_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      1,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "disconnect",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_disconnect_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_disconnect_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) OpenFile(ctx context.Context, params func(EditorService_openFile_Params) error) (EditorService_openFile_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      2,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "openFile",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_openFile_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_openFile_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) GetUpdates(ctx context.Context, params func(EditorService_getUpdates_Params) error) (EditorService_getUpdates_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      3,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "getUpdates",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 24, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_getUpdates_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_getUpdates_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) ApplyOp(ctx context.Context, params func(EditorService_applyOp_Params) error) (EditorService_applyOp_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      4,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "applyOp",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_applyOp_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_applyOp_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) Save(ctx context.Context, params func(EditorService_save_Params) error) (EditorService_save_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      5,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "save",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_save_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_save_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) CloseBuffer(ctx context.Context, params func(EditorService_closeBuffer_Params) error) (EditorService_closeBuffer_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      6,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "closeBuffer",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_closeBuffer_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_closeBuffer_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) BufferClientCount(ctx context.Context, params func(EditorService_bufferClientCount_Params) error) (EditorService_bufferClientCount_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      7,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "bufferClientCount",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_bufferClientCount_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_bufferClientCount_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) DiscardRecovery(ctx context.Context, params func(EditorService_discardRecovery_Params) error) (EditorService_discardRecovery_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      8,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "discardRecovery",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EditorService_discardRecovery_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EditorService_discardRecovery_Results_Future{Future: ans.Future()}, release

}

func (c EditorService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c EditorService) String() string {
	return "EditorService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c EditorService) AddRef() EditorService {
	return EditorService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c EditorService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c EditorService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c EditorService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (EditorService) DecodeFromPtr(p capnp.Ptr) EditorService {
	return EditorService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c EditorService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c EditorService) IsSame(other EditorService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c EditorService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c EditorService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A EditorService_Server is a EditorService with a local implementation.
type EditorService_Server interface {
	Connect(context.Context, EditorService_connect) error

	Disconnect(context.Context, EditorService_disconnect) error

	OpenFile(context.Context, EditorService_openFile) error

	GetUpdates(context.Context, EditorService_getUpdates) error

	ApplyOp(context.Context, EditorService_applyOp) error

	Save(context.Context, EditorService_save) error

	CloseBuffer(context.Context, EditorService_closeBuffer) error

	BufferClientCount(context.Context, EditorService_bufferClientCount) error

	DiscardRecovery(context.Context, EditorService_discardRecovery) error
}

// EditorService_NewServer creates a new Server from an implementation of EditorService_Server.
func EditorService_NewServer(s EditorService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(EditorService_Methods(nil, s), s, c)
}

// EditorService_ServerToClient creates a new Client from an implementation of EditorService_Server.
// The caller is responsible for calling Release on the returned Client.
func EditorService_ServerToClient(s EditorService_Server) EditorService {
	return EditorService(capnp.NewClient(EditorService_NewServer(s)))
}

// EditorService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func EditorService_Methods(methods []server.Method, s EditorService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 9)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      0,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "connect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Connect(ctx, EditorService_connect{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      1,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "disconnect",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Disconnect(ctx, EditorService_disconnect{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      2,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "openFile",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.OpenFile(ctx, EditorService_openFile{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      3,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "getUpdates",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.GetUpdates(ctx, EditorService_getUpdates{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      4,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "applyOp",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.ApplyOp(ctx, EditorService_applyOp{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      5,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "save",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Save(ctx, EditorService_save{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      6,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "closeBuffer",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.CloseBuffer(ctx, EditorService_closeBuffer{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      7,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "bufferClientCount",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.BufferClientCount(ctx, EditorService_bufferClientCount{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd281f133906f9f01,
			MethodID:      8,
			InterfaceName: "editor.capnp:EditorService",
			MethodName:    "discardRecovery",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.DiscardRecovery(ctx, EditorService_discardRecovery{call})
		},
	})

	return methods
}

// EditorService_connect holds the state for a server call to EditorService.connect.
// See server.Call for documentation.
type EditorService_connect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_connect) Args() EditorService_connect_Params {
	return EditorService_connect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_connect) AllocResults() (EditorService_connect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(r), err
}

// EditorService_disconnect holds the state for a server call to EditorService.disconnect.
// See server.Call for documentation.
type EditorService_disconnect struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_disconnect) Args() EditorService_disconnect_Params {
	return EditorService_disconnect_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_disconnect) AllocResults() (EditorService_disconnect_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(r), err
}

// EditorService_openFile holds the state for a server call to EditorService.openFile.
// See server.Call for documentation.
type EditorService_openFile struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_openFile) Args() EditorService_openFile_Params {
	return EditorService_openFile_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_openFile) AllocResults() (EditorService_openFile_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(r), err
}

// EditorService_getUpdates holds the state for a server call to EditorService.getUpdates.
// See server.Call for documentation.
type EditorService_getUpdates struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_getUpdates) Args() EditorService_getUpdates_Params {
	return EditorService_getUpdates_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_getUpdates) AllocResults() (EditorService_getUpdates_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(r), err
}

// EditorService_applyOp holds the state for a server call to EditorService.applyOp.
// See server.Call for documentation.
type EditorService_applyOp struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_applyOp) Args() EditorService_applyOp_Params {
	return EditorService_applyOp_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_applyOp) AllocResults() (EditorService_applyOp_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(r), err
}

// EditorService_save holds the state for a server call to EditorService.save.
// See server.Call for documentation.
type EditorService_save struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_save) Args() EditorService_save_Params {
	return EditorService_save_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_save) AllocResults() (EditorService_save_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(r), err
}

// EditorService_closeBuffer holds the state for a server call to EditorService.closeBuffer.
// See server.Call for documentation.
type EditorService_closeBuffer struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_closeBuffer) Args() EditorService_closeBuffer_Params {
	return EditorService_closeBuffer_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_closeBuffer) AllocResults() (EditorService_closeBuffer_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(r), err
}

// EditorService_bufferClientCount holds the state for a server call to EditorService.bufferClientCount.
// See server.Call for documentation.
type EditorService_bufferClientCount struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_bufferClientCount) Args() EditorService_bufferClientCount_Params {
	return EditorService_bufferClientCount_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_bufferClientCount) AllocResults() (EditorService_bufferClientCount_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(r), err
}

// EditorService_discardRecovery holds the state for a server call to EditorService.discardRecovery.
// See server.Call for documentation.
type EditorService_discardRecovery struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EditorService_discardRecovery) Args() EditorService_discardRecovery_Params {
	return EditorService_discardRecovery_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EditorService_discardRecovery) AllocResults() (EditorService_discardRecovery_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EditorService_discardRecovery_Results(r), err
}

// EditorService_List is a list of EditorService.
type EditorService_List = capnp.CapList[EditorService]

// NewEditorService_List creates a new list of EditorService.
func NewEditorService_List(s *capnp.Segment, sz int32) (EditorService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[EditorService](l), err
}

type EditorService_connect_Params capnp.Struct

// EditorService_connect_Params_TypeID is the unique identifier for the type EditorService_connect_Params.
const EditorService_connect_Params_TypeID = 0xe4418928851d24b2

func NewEditorService_connect_Params(s *capnp.Segment) (EditorService_connect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_connect_Params(st), err
}

func NewRootEditorService_connect_Params(s *capnp.Segment) (EditorService_connect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_connect_Params(st), err
}

func ReadRootEditorService_connect_Params(msg *capnp.Message) (EditorService_connect_Params, error) {
	root, err := msg.Root()
	return EditorService_connect_Params(root.Struct()), err
}

func (s EditorService_connect_Params) String() string {
	str, _ := text.Marshal(0xe4418928851d24b2, capnp.Struct(s))
	return str
}

func (s EditorService_connect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_connect_Params) DecodeFromPtr(p capnp.Ptr) EditorService_connect_Params {
	return EditorService_connect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_connect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_connect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_connect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_connect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_connect_Params_List is a list of EditorService_connect_Params.
type EditorService_connect_Params_List = capnp.StructList[EditorService_connect_Params]

// NewEditorService_connect_Params creates a new list of EditorService_connect_Params.
func NewEditorService_connect_Params_List(s *capnp.Segment, sz int32) (EditorService_connect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_connect_Params](l), err
}

// EditorService_connect_Params_Future is a wrapper for a EditorService_connect_Params promised by a client call.
type EditorService_connect_Params_Future struct{ *capnp.Future }

func (f EditorService_connect_Params_Future) Struct() (EditorService_connect_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_connect_Params(p.Struct()), err
}

type EditorService_connect_Results capnp.Struct

// EditorService_connect_Results_TypeID is the unique identifier for the type EditorService_connect_Results.
const EditorService_connect_Results_TypeID = 0xf837e3273ba4c201

func NewEditorService_connect_Results(s *capnp.Segment) (EditorService_connect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(st), err
}

func NewRootEditorService_connect_Results(s *capnp.Segment) (EditorService_connect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_connect_Results(st), err
}

func ReadRootEditorService_connect_Results(msg *capnp.Message) (EditorService_connect_Results, error) {
	root, err := msg.Root()
	return EditorService_connect_Results(root.Struct()), err
}

func (s EditorService_connect_Results) String() string {
	str, _ := text.Marshal(0xf837e3273ba4c201, capnp.Struct(s))
	return str
}

func (s EditorService_connect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_connect_Results) DecodeFromPtr(p capnp.Ptr) EditorService_connect_Results {
	return EditorService_connect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_connect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_connect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_connect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_connect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_connect_Results) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_connect_Results) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_connect_Results_List is a list of EditorService_connect_Results.
type EditorService_connect_Results_List = capnp.StructList[EditorService_connect_Results]

// NewEditorService_connect_Results creates a new list of EditorService_connect_Results.
func NewEditorService_connect_Results_List(s *capnp.Segment, sz int32) (EditorService_connect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_connect_Results](l), err
}

// EditorService_connect_Results_Future is a wrapper for a EditorService_connect_Results promised by a client call.
type EditorService_connect_Results_Future struct{ *capnp.Future }

func (f EditorService_connect_Results_Future) Struct() (EditorService_connect_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_connect_Results(p.Struct()), err
}

type EditorService_disconnect_Params capnp.Struct

// EditorService_disconnect_Params_TypeID is the unique identifier for the type EditorService_disconnect_Params.
const EditorService_disconnect_Params_TypeID = 0xfdaeb62e8f10b2ff

func NewEditorService_disconnect_Params(s *capnp.Segment) (EditorService_disconnect_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_disconnect_Params(st), err
}

func NewRootEditorService_disconnect_Params(s *capnp.Segment) (EditorService_disconnect_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_disconnect_Params(st), err
}

func ReadRootEditorService_disconnect_Params(msg *capnp.Message) (EditorService_disconnect_Params, error) {
	root, err := msg.Root()
	return EditorService_disconnect_Params(root.Struct()), err
}

func (s EditorService_disconnect_Params) String() string {
	str, _ := text.Marshal(0xfdaeb62e8f10b2ff, capnp.Struct(s))
	return str
}

func (s EditorService_disconnect_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_disconnect_Params) DecodeFromPtr(p capnp.Ptr) EditorService_disconnect_Params {
	return EditorService_disconnect_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_disconnect_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_disconnect_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_disconnect_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_disconnect_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_disconnect_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_disconnect_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_disconnect_Params_List is a list of EditorService_disconnect_Params.
type EditorService_disconnect_Params_List = capnp.StructList[EditorService_disconnect_Params]

// NewEditorService_disconnect_Params creates a new list of EditorService_disconnect_Params.
func NewEditorService_disconnect_Params_List(s *capnp.Segment, sz int32) (EditorService_disconnect_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_disconnect_Params](l), err
}

// EditorService_disconnect_Params_Future is a wrapper for a EditorService_disconnect_Params promised by a client call.
type EditorService_disconnect_Params_Future struct{ *capnp.Future }

func (f EditorService_disconnect_Params_Future) Struct() (EditorService_disconnect_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_disconnect_Params(p.Struct()), err
}

type EditorService_disconnect_Results capnp.Struct

// EditorService_disconnect_Results_TypeID is the unique identifier for the type EditorService_disconnect_Results.
const EditorService_disconnect_Results_TypeID = 0xf3842bc6cf4149eb

func NewEditorService_disconnect_Results(s *capnp.Segment) (EditorService_disconnect_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(st), err
}

func NewRootEditorService_disconnect_Results(s *capnp.Segment) (EditorService_disconnect_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_disconnect_Results(st), err
}

func ReadRootEditorService_disconnect_Results(msg *capnp.Message) (EditorService_disconnect_Results, error) {
	root, err := msg.Root()
	return EditorService_disconnect_Results(root.Struct()), err
}

func (s EditorService_disconnect_Results) String() string {
	str, _ := text.Marshal(0xf3842bc6cf4149eb, capnp.Struct(s))
	return str
}

func (s EditorService_disconnect_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_disconnect_Results) DecodeFromPtr(p capnp.Ptr) EditorService_disconnect_Results {
	return EditorService_disconnect_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_disconnect_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_disconnect_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_disconnect_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_disconnect_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_disconnect_Results_List is a list of EditorService_disconnect_Results.
type EditorService_disconnect_Results_List = capnp.StructList[EditorService_disconnect_Results]

// NewEditorService_disconnect_Results creates a new list of EditorService_disconnect_Results.
func NewEditorService_disconnect_Results_List(s *capnp.Segment, sz int32) (EditorService_disconnect_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_disconnect_Results](l), err
}

// EditorService_disconnect_Results_Future is a wrapper for a EditorService_disconnect_Results promised by a client call.
type EditorService_disconnect_Results_Future struct{ *capnp.Future }

func (f EditorService_disconnect_Results_Future) Struct() (EditorService_disconnect_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_disconnect_Results(p.Struct()), err
}

type EditorService_openFile_Params capnp.Struct

// EditorService_openFile_Params_TypeID is the unique identifier for the type EditorService_openFile_Params.
const EditorService_openFile_Params_TypeID = 0xcd6d4043f1fd9e2d

func NewEditorService_openFile_Params(s *capnp.Segment) (EditorService_openFile_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_openFile_Params(st), err
}

func NewRootEditorService_openFile_Params(s *capnp.Segment) (EditorService_openFile_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_openFile_Params(st), err
}

func ReadRootEditorService_openFile_Params(msg *capnp.Message) (EditorService_openFile_Params, error) {
	root, err := msg.Root()
	return EditorService_openFile_Params(root.Struct()), err
}

func (s EditorService_openFile_Params) String() string {
	str, _ := text.Marshal(0xcd6d4043f1fd9e2d, capnp.Struct(s))
	return str
}

func (s EditorService_openFile_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_openFile_Params) DecodeFromPtr(p capnp.Ptr) EditorService_openFile_Params {
	return EditorService_openFile_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_openFile_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_openFile_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_openFile_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_openFile_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_openFile_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_openFile_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_openFile_Params) Path() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditorService_openFile_Params) HasPath() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_openFile_Params) PathBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditorService_openFile_Params) SetPath(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// EditorService_openFile_Params_List is a list of EditorService_openFile_Params.
type EditorService_openFile_Params_List = capnp.StructList[EditorService_openFile_Params]

// NewEditorService_openFile_Params creates a new list of EditorService_openFile_Params.
func NewEditorService_openFile_Params_List(s *capnp.Segment, sz int32) (EditorService_openFile_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_openFile_Params](l), err
}

// EditorService_openFile_Params_Future is a wrapper for a EditorService_openFile_Params promised by a client call.
type EditorService_openFile_Params_Future struct{ *capnp.Future }

func (f EditorService_openFile_Params_Future) Struct() (EditorService_openFile_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_openFile_Params(p.Struct()), err
}

type EditorService_openFile_Results capnp.Struct

// EditorService_openFile_Results_TypeID is the unique identifier for the type EditorService_openFile_Results.
const EditorService_openFile_Results_TypeID = 0x9881b45d79299b22

func NewEditorService_openFile_Results(s *capnp.Segment) (EditorService_openFile_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(st), err
}

func NewRootEditorService_openFile_Results(s *capnp.Segment) (EditorService_openFile_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_openFile_Results(st), err
}

func ReadRootEditorService_openFile_Results(msg *capnp.Message) (EditorService_openFile_Results, error) {
	root, err := msg.Root()
	return EditorService_openFile_Results(root.Struct()), err
}

func (s EditorService_openFile_Results) String() string {
	str, _ := text.Marshal(0x9881b45d79299b22, capnp.Struct(s))
	return str
}

func (s EditorService_openFile_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_openFile_Results) DecodeFromPtr(p capnp.Ptr) EditorService_openFile_Results {
	return EditorService_openFile_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_openFile_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_openFile_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_openFile_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_openFile_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_openFile_Results) BufferId() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_openFile_Results) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

func (s EditorService_openFile_Results) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditorService_openFile_Results) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_openFile_Results) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditorService_openFile_Results) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EditorService_openFile_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EditorService_openFile_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EditorService_openFile_Results) FromRecovery() bool {
	return capnp.Struct(s).Bit(32)
}

func (s EditorService_openFile_Results) SetFromRecovery(v bool) {
	capnp.Struct(s).SetBit(32, v)
}

// EditorService_openFile_Results_List is a list of EditorService_openFile_Results.
type EditorService_openFile_Results_List = capnp.StructList[EditorService_openFile_Results]

// NewEditorService_openFile_Results creates a new list of EditorService_openFile_Results.
func NewEditorService_openFile_Results_List(s *capnp.Segment, sz int32) (EditorService_openFile_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_openFile_Results](l), err
}

// EditorService_openFile_Results_Future is a wrapper for a EditorService_openFile_Results promised by a client call.
type EditorService_openFile_Results_Future struct{ *capnp.Future }

func (f EditorService_openFile_Results_Future) Struct() (EditorService_openFile_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_openFile_Results(p.Struct()), err
}

type EditorService_getUpdates_Params capnp.Struct

// EditorService_getUpdates_Params_TypeID is the unique identifier for the type EditorService_getUpdates_Params.
const EditorService_getUpdates_Params_TypeID = 0xb3c8a09d8d7f2391

func NewEditorService_getUpdates_Params(s *capnp.Segment) (EditorService_getUpdates_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EditorService_getUpdates_Params(st), err
}

func NewRootEditorService_getUpdates_Params(s *capnp.Segment) (EditorService_getUpdates_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return EditorService_getUpdates_Params(st), err
}

func ReadRootEditorService_getUpdates_Params(msg *capnp.Message) (EditorService_getUpdates_Params, error) {
	root, err := msg.Root()
	return EditorService_getUpdates_Params(root.Struct()), err
}

func (s EditorService_getUpdates_Params) String() string {
	str, _ := text.Marshal(0xb3c8a09d8d7f2391, capnp.Struct(s))
	return str
}

func (s EditorService_getUpdates_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_getUpdates_Params) DecodeFromPtr(p capnp.Ptr) EditorService_getUpdates_Params {
	return EditorService_getUpdates_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_getUpdates_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_getUpdates_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_getUpdates_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_getUpdates_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_getUpdates_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_getUpdates_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_getUpdates_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_getUpdates_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s EditorService_getUpdates_Params) SinceVersion() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s EditorService_getUpdates_Params) SetSinceVersion(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// EditorService_getUpdates_Params_List is a list of EditorService_getUpdates_Params.
type EditorService_getUpdates_Params_List = capnp.StructList[EditorService_getUpdates_Params]

// NewEditorService_getUpdates_Params creates a new list of EditorService_getUpdates_Params.
func NewEditorService_getUpdates_Params_List(s *capnp.Segment, sz int32) (EditorService_getUpdates_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_getUpdates_Params](l), err
}

// EditorService_getUpdates_Params_Future is a wrapper for a EditorService_getUpdates_Params promised by a client call.
type EditorService_getUpdates_Params_Future struct{ *capnp.Future }

func (f EditorService_getUpdates_Params_Future) Struct() (EditorService_getUpdates_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_getUpdates_Params(p.Struct()), err
}

type EditorService_getUpdates_Results capnp.Struct

// EditorService_getUpdates_Results_TypeID is the unique identifier for the type EditorService_getUpdates_Results.
const EditorService_getUpdates_Results_TypeID = 0xdc19fdc1e173fe90

func NewEditorService_getUpdates_Results(s *capnp.Segment) (EditorService_getUpdates_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(st), err
}

func NewRootEditorService_getUpdates_Results(s *capnp.Segment) (EditorService_getUpdates_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return EditorService_getUpdates_Results(st), err
}

func ReadRootEditorService_getUpdates_Results(msg *capnp.Message) (EditorService_getUpdates_Results, error) {
	root, err := msg.Root()
	return EditorService_getUpdates_Results(root.Struct()), err
}

func (s EditorService_getUpdates_Results) String() string {
	str, _ := text.Marshal(0xdc19fdc1e173fe90, capnp.Struct(s))
	return str
}

func (s EditorService_getUpdates_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_getUpdates_Results) DecodeFromPtr(p capnp.Ptr) EditorService_getUpdates_Results {
	return EditorService_getUpdates_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_getUpdates_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_getUpdates_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_getUpdates_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_getUpdates_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_getUpdates_Results) Ops() (EditOp_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EditOp_List(p.List()), err
}

func (s EditorService_getUpdates_Results) HasOps() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_getUpdates_Results) SetOps(v EditOp_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewOps sets the ops field to a newly
// allocated EditOp_List, preferring placement in s's segment.
func (s EditorService_getUpdates_Results) NewOps(n int32) (EditOp_List, error) {
	l, err := NewEditOp_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return EditOp_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s EditorService_getUpdates_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_getUpdates_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_getUpdates_Results_List is a list of EditorService_getUpdates_Results.
type EditorService_getUpdates_Results_List = capnp.StructList[EditorService_getUpdates_Results]

// NewEditorService_getUpdates_Results creates a new list of EditorService_getUpdates_Results.
func NewEditorService_getUpdates_Results_List(s *capnp.Segment, sz int32) (EditorService_getUpdates_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_getUpdates_Results](l), err
}

// EditorService_getUpdates_Results_Future is a wrapper for a EditorService_getUpdates_Results promised by a client call.
type EditorService_getUpdates_Results_Future struct{ *capnp.Future }

func (f EditorService_getUpdates_Results_Future) Struct() (EditorService_getUpdates_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_getUpdates_Results(p.Struct()), err
}

type EditorService_applyOp_Params capnp.Struct

// EditorService_applyOp_Params_TypeID is the unique identifier for the type EditorService_applyOp_Params.
const EditorService_applyOp_Params_TypeID = 0x81f9af23ee6aa27e

func NewEditorService_applyOp_Params(s *capnp.Segment) (EditorService_applyOp_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_applyOp_Params(st), err
}

func NewRootEditorService_applyOp_Params(s *capnp.Segment) (EditorService_applyOp_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return EditorService_applyOp_Params(st), err
}

func ReadRootEditorService_applyOp_Params(msg *capnp.Message) (EditorService_applyOp_Params, error) {
	root, err := msg.Root()
	return EditorService_applyOp_Params(root.Struct()), err
}

func (s EditorService_applyOp_Params) String() string {
	str, _ := text.Marshal(0x81f9af23ee6aa27e, capnp.Struct(s))
	return str
}

func (s EditorService_applyOp_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_applyOp_Params) DecodeFromPtr(p capnp.Ptr) EditorService_applyOp_Params {
	return EditorService_applyOp_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_applyOp_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_applyOp_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_applyOp_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_applyOp_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_applyOp_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_applyOp_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_applyOp_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_applyOp_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

func (s EditorService_applyOp_Params) Op() (EditOp, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EditOp(p.Struct()), err
}

func (s EditorService_applyOp_Params) HasOp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_applyOp_Params) SetOp(v EditOp) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewOp sets the op field to a newly
// allocated EditOp struct, preferring placement in s's segment.
func (s EditorService_applyOp_Params) NewOp() (EditOp, error) {
	ss, err := NewEditOp(capnp.Struct(s).Segment())
	if err != nil {
		return EditOp{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EditorService_applyOp_Params_List is a list of EditorService_applyOp_Params.
type EditorService_applyOp_Params_List = capnp.StructList[EditorService_applyOp_Params]

// NewEditorService_applyOp_Params creates a new list of EditorService_applyOp_Params.
func NewEditorService_applyOp_Params_List(s *capnp.Segment, sz int32) (EditorService_applyOp_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_applyOp_Params](l), err
}

// EditorService_applyOp_Params_Future is a wrapper for a EditorService_applyOp_Params promised by a client call.
type EditorService_applyOp_Params_Future struct{ *capnp.Future }

func (f EditorService_applyOp_Params_Future) Struct() (EditorService_applyOp_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_applyOp_Params(p.Struct()), err
}
func (p EditorService_applyOp_Params_Future) Op() EditOp_Future {
	return EditOp_Future{Future: p.Future.Field(0, nil)}
}

type EditorService_applyOp_Results capnp.Struct

// EditorService_applyOp_Results_TypeID is the unique identifier for the type EditorService_applyOp_Results.
const EditorService_applyOp_Results_TypeID = 0xbef0f62b1a5ccab5

func NewEditorService_applyOp_Results(s *capnp.Segment) (EditorService_applyOp_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(st), err
}

func NewRootEditorService_applyOp_Results(s *capnp.Segment) (EditorService_applyOp_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_applyOp_Results(st), err
}

func ReadRootEditorService_applyOp_Results(msg *capnp.Message) (EditorService_applyOp_Results, error) {
	root, err := msg.Root()
	return EditorService_applyOp_Results(root.Struct()), err
}

func (s EditorService_applyOp_Results) String() string {
	str, _ := text.Marshal(0xbef0f62b1a5ccab5, capnp.Struct(s))
	return str
}

func (s EditorService_applyOp_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_applyOp_Results) DecodeFromPtr(p capnp.Ptr) EditorService_applyOp_Results {
	return EditorService_applyOp_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_applyOp_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_applyOp_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_applyOp_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_applyOp_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_applyOp_Results) Version() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_applyOp_Results) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// EditorService_applyOp_Results_List is a list of EditorService_applyOp_Results.
type EditorService_applyOp_Results_List = capnp.StructList[EditorService_applyOp_Results]

// NewEditorService_applyOp_Results creates a new list of EditorService_applyOp_Results.
func NewEditorService_applyOp_Results_List(s *capnp.Segment, sz int32) (EditorService_applyOp_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_applyOp_Results](l), err
}

// EditorService_applyOp_Results_Future is a wrapper for a EditorService_applyOp_Results promised by a client call.
type EditorService_applyOp_Results_Future struct{ *capnp.Future }

func (f EditorService_applyOp_Results_Future) Struct() (EditorService_applyOp_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_applyOp_Results(p.Struct()), err
}

type EditorService_save_Params capnp.Struct

// EditorService_save_Params_TypeID is the unique identifier for the type EditorService_save_Params.
const EditorService_save_Params_TypeID = 0xdd178a12d938882b

func NewEditorService_save_Params(s *capnp.Segment) (EditorService_save_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_save_Params(st), err
}

func NewRootEditorService_save_Params(s *capnp.Segment) (EditorService_save_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_save_Params(st), err
}

func ReadRootEditorService_save_Params(msg *capnp.Message) (EditorService_save_Params, error) {
	root, err := msg.Root()
	return EditorService_save_Params(root.Struct()), err
}

func (s EditorService_save_Params) String() string {
	str, _ := text.Marshal(0xdd178a12d938882b, capnp.Struct(s))
	return str
}

func (s EditorService_save_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_save_Params) DecodeFromPtr(p capnp.Ptr) EditorService_save_Params {
	return EditorService_save_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_save_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_save_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_save_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_save_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_save_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_save_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_save_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_save_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// EditorService_save_Params_List is a list of EditorService_save_Params.
type EditorService_save_Params_List = capnp.StructList[EditorService_save_Params]

// NewEditorService_save_Params creates a new list of EditorService_save_Params.
func NewEditorService_save_Params_List(s *capnp.Segment, sz int32) (EditorService_save_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_save_Params](l), err
}

// EditorService_save_Params_Future is a wrapper for a EditorService_save_Params promised by a client call.
type EditorService_save_Params_Future struct{ *capnp.Future }

func (f EditorService_save_Params_Future) Struct() (EditorService_save_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_save_Params(p.Struct()), err
}

type EditorService_save_Results capnp.Struct

// EditorService_save_Results_TypeID is the unique identifier for the type EditorService_save_Results.
const EditorService_save_Results_TypeID = 0x8089f48db0346b82

func NewEditorService_save_Results(s *capnp.Segment) (EditorService_save_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(st), err
}

func NewRootEditorService_save_Results(s *capnp.Segment) (EditorService_save_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_save_Results(st), err
}

func ReadRootEditorService_save_Results(msg *capnp.Message) (EditorService_save_Results, error) {
	root, err := msg.Root()
	return EditorService_save_Results(root.Struct()), err
}

func (s EditorService_save_Results) String() string {
	str, _ := text.Marshal(0x8089f48db0346b82, capnp.Struct(s))
	return str
}

func (s EditorService_save_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_save_Results) DecodeFromPtr(p capnp.Ptr) EditorService_save_Results {
	return EditorService_save_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_save_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_save_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_save_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_save_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_save_Results_List is a list of EditorService_save_Results.
type EditorService_save_Results_List = capnp.StructList[EditorService_save_Results]

// NewEditorService_save_Results creates a new list of EditorService_save_Results.
func NewEditorService_save_Results_List(s *capnp.Segment, sz int32) (EditorService_save_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_save_Results](l), err
}

// EditorService_save_Results_Future is a wrapper for a EditorService_save_Results promised by a client call.
type EditorService_save_Results_Future struct{ *capnp.Future }

func (f EditorService_save_Results_Future) Struct() (EditorService_save_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_save_Results(p.Struct()), err
}

type EditorService_closeBuffer_Params capnp.Struct

// EditorService_closeBuffer_Params_TypeID is the unique identifier for the type EditorService_closeBuffer_Params.
const EditorService_closeBuffer_Params_TypeID = 0xca42a841ee65eea6

func NewEditorService_closeBuffer_Params(s *capnp.Segment) (EditorService_closeBuffer_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_closeBuffer_Params(st), err
}

func NewRootEditorService_closeBuffer_Params(s *capnp.Segment) (EditorService_closeBuffer_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_closeBuffer_Params(st), err
}

func ReadRootEditorService_closeBuffer_Params(msg *capnp.Message) (EditorService_closeBuffer_Params, error) {
	root, err := msg.Root()
	return EditorService_closeBuffer_Params(root.Struct()), err
}

func (s EditorService_closeBuffer_Params) String() string {
	str, _ := text.Marshal(0xca42a841ee65eea6, capnp.Struct(s))
	return str
}

func (s EditorService_closeBuffer_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_closeBuffer_Params) DecodeFromPtr(p capnp.Ptr) EditorService_closeBuffer_Params {
	return EditorService_closeBuffer_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_closeBuffer_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_closeBuffer_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_closeBuffer_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_closeBuffer_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_closeBuffer_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_closeBuffer_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_closeBuffer_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_closeBuffer_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// EditorService_closeBuffer_Params_List is a list of EditorService_closeBuffer_Params.
type EditorService_closeBuffer_Params_List = capnp.StructList[EditorService_closeBuffer_Params]

// NewEditorService_closeBuffer_Params creates a new list of EditorService_closeBuffer_Params.
func NewEditorService_closeBuffer_Params_List(s *capnp.Segment, sz int32) (EditorService_closeBuffer_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_closeBuffer_Params](l), err
}

// EditorService_closeBuffer_Params_Future is a wrapper for a EditorService_closeBuffer_Params promised by a client call.
type EditorService_closeBuffer_Params_Future struct{ *capnp.Future }

func (f EditorService_closeBuffer_Params_Future) Struct() (EditorService_closeBuffer_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_closeBuffer_Params(p.Struct()), err
}

type EditorService_closeBuffer_Results capnp.Struct

// EditorService_closeBuffer_Results_TypeID is the unique identifier for the type EditorService_closeBuffer_Results.
const EditorService_closeBuffer_Results_TypeID = 0xbc963afed2baaec8

func NewEditorService_closeBuffer_Results(s *capnp.Segment) (EditorService_closeBuffer_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(st), err
}

func NewRootEditorService_closeBuffer_Results(s *capnp.Segment) (EditorService_closeBuffer_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return EditorService_closeBuffer_Results(st), err
}

func ReadRootEditorService_closeBuffer_Results(msg *capnp.Message) (EditorService_closeBuffer_Results, error) {
	root, err := msg.Root()
	return EditorService_closeBuffer_Results(root.Struct()), err
}

func (s EditorService_closeBuffer_Results) String() string {
	str, _ := text.Marshal(0xbc963afed2baaec8, capnp.Struct(s))
	return str
}

func (s EditorService_closeBuffer_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_closeBuffer_Results) DecodeFromPtr(p capnp.Ptr) EditorService_closeBuffer_Results {
	return EditorService_closeBuffer_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_closeBuffer_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_closeBuffer_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_closeBuffer_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_closeBuffer_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// EditorService_closeBuffer_Results_List is a list of EditorService_closeBuffer_Results.
type EditorService_closeBuffer_Results_List = capnp.StructList[EditorService_closeBuffer_Results]

// NewEditorService_closeBuffer_Results creates a new list of EditorService_closeBuffer_Results.
func NewEditorService_closeBuffer_Results_List(s *capnp.Segment, sz int32) (EditorService_closeBuffer_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_closeBuffer_Results](l), err
}

// EditorService_closeBuffer_Results_Future is a wrapper for a EditorService_closeBuffer_Results promised by a client call.
type EditorService_closeBuffer_Results_Future struct{ *capnp.Future }

func (f EditorService_closeBuffer_Results_Future) Struct() (EditorService_closeBuffer_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_closeBuffer_Results(p.Struct()), err
}

type EditorService_bufferClientCount_Params capnp.Struct

// EditorService_bufferClientCount_Params_TypeID is the unique identifier for the type EditorService_bufferClientCount_Params.
const EditorService_bufferClientCount_Params_TypeID = 0xe8abb7e7f38eda68

func NewEditorService_bufferClientCount_Params(s *capnp.Segment) (EditorService_bufferClientCount_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Params(st), err
}

func NewRootEditorService_bufferClientCount_Params(s *capnp.Segment) (EditorService_bufferClientCount_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Params(st), err
}

func ReadRootEditorService_bufferClientCount_Params(msg *capnp.Message) (EditorService_bufferClientCount_Params, error) {
	root, err := msg.Root()
	return EditorService_bufferClientCount_Params(root.Struct()), err
}

func (s EditorService_bufferClientCount_Params) String() string {
	str, _ := text.Marshal(0xe8abb7e7f38eda68, capnp.Struct(s))
	return str
}

func (s EditorService_bufferClientCount_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_bufferClientCount_Params) DecodeFromPtr(p capnp.Ptr) EditorService_bufferClientCount_Params {
	return EditorService_bufferClientCount_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_bufferClientCount_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_bufferClientCount_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_bufferClientCount_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_bufferClientCount_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_bufferClientCount_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_bufferClientCount_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// EditorService_bufferClientCount_Params_List is a list of EditorService_bufferClientCount_Params.
type EditorService_bufferClientCount_Params_List = capnp.StructList[EditorService_bufferClientCount_Params]

// NewEditorService_bufferClientCount_Params creates a new list of EditorService_bufferClientCount_Params.
func NewEditorService_bufferClientCount_Params_List(s *capnp.Segment, sz int32) (EditorService_bufferClientCount_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_bufferClientCount_Params](l), err
}

// EditorService_bufferClientCount_Params_Future is a wrapper for a EditorService_bufferClientCount_Params promised by a client call.
type EditorService_bufferClientCount_Params_Future struct{ *capnp.Future }

func (f EditorService_bufferClientCount_Params_Future) Struct() (EditorService_bufferClientCount_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_bufferClientCount_Params(p.Struct()), err
}

type EditorService_bufferClientCount_Results capnp.Struct

// EditorService_bufferClientCount_Results_TypeID is the unique identifier for the type EditorService_bufferClientCount_Results.
const EditorService_bufferClientCount_Results_TypeID = 0xcdecfd1a01f89461

func NewEditorService_bufferClientCount_Results(s *capnp.Segment) (EditorService_bufferClientCount_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(st), err
}

func NewRootEditorService_bufferClientCount_Results(s *capnp.Segment) (EditorService_bufferClientCount_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return EditorService_bufferClientCount_Results(st), err
}

func ReadRootEditorService_bufferClientCount_Results(msg *capnp.Message) (EditorService_bufferClientCount_Results, error) {
	root, err := msg.Root()
	return EditorService_bufferClientCount_Results(root.Struct()), err
}

func (s EditorService_bufferClientCount_Results) String() string {
	str, _ := text.Marshal(0xcdecfd1a01f89461, capnp.Struct(s))
	return str
}

func (s EditorService_bufferClientCount_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_bufferClientCount_Results) DecodeFromPtr(p capnp.Ptr) EditorService_bufferClientCount_Results {
	return EditorService_bufferClientCount_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_bufferClientCount_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_bufferClientCount_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_bufferClientCount_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_bufferClientCount_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_bufferClientCount_Results) Count() uint32 {
	return capnp.Struct(s).Uint32(0)
}

func (s EditorService_bufferClientCount_Results) SetCount(v uint32) {
	capnp.Struct(s).SetUint32(0, v)
}

// EditorService_bufferClientCount_Results_List is a list of EditorService_bufferClientCount_Results.
type EditorService_bufferClientCount_Results_List = capnp.StructList[EditorService_bufferClientCount_Results]

// NewEditorService_bufferClientCount_Results creates a new list of EditorService_bufferClientCount_Results.
func NewEditorService_bufferClientCount_Results_List(s *capnp.Segment, sz int32) (EditorService_bufferClientCount_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_bufferClientCount_Results](l), err
}

// EditorService_bufferClientCount_Results_Future is a wrapper for a EditorService_bufferClientCount_Results promised by a client call.
type EditorService_bufferClientCount_Results_Future struct{ *capnp.Future }

func (f EditorService_bufferClientCount_Results_Future) Struct() (EditorService_bufferClientCount_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_bufferClientCount_Results(p.Struct()), err
}

type EditorService_discardRecovery_Params capnp.Struct

// EditorService_discardRecovery_Params_TypeID is the unique identifier for the type EditorService_discardRecovery_Params.
const EditorService_discardRecovery_Params_TypeID = 0xaed406d1812d9f83

func NewEditorService_discardRecovery_Params(s *capnp.Segment) (EditorService_discardRecovery_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_discardRecovery_Params(st), err
}

func NewRootEditorService_discardRecovery_Params(s *capnp.Segment) (EditorService_discardRecovery_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return EditorService_discardRecovery_Params(st), err
}

func ReadRootEditorService_discardRecovery_Params(msg *capnp.Message) (EditorService_discardRecovery_Params, error) {
	root, err := msg.Root()
	return EditorService_discardRecovery_Params(root.Struct()), err
}

func (s EditorService_discardRecovery_Params) String() string {
	str, _ := text.Marshal(0xaed406d1812d9f83, capnp.Struct(s))
	return str
}

func (s EditorService_discardRecovery_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_discardRecovery_Params) DecodeFromPtr(p capnp.Ptr) EditorService_discardRecovery_Params {
	return EditorService_discardRecovery_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_discardRecovery_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_discardRecovery_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_discardRecovery_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_discardRecovery_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_discardRecovery_Params) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditorService_discardRecovery_Params) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditorService_discardRecovery_Params) BufferId() uint32 {
	return capnp.Struct(s).Uint32(8)
}

func (s EditorService_discardRecovery_Params) SetBufferId(v uint32) {
	capnp.Struct(s).SetUint32(8, v)
}

// EditorService_discardRecovery_Params_List is a list of EditorService_discardRecovery_Params.
type EditorService_discardRecovery_Params_List = capnp.StructList[EditorService_discardRecovery_Params]

// NewEditorService_discardRecovery_Params creates a new list of EditorService_discardRecovery_Params.
func NewEditorService_discardRecovery_Params_List(s *capnp.Segment, sz int32) (EditorService_discardRecovery_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[EditorService_discardRecovery_Params](l), err
}

// EditorService_discardRecovery_Params_Future is a wrapper for a EditorService_discardRecovery_Params promised by a client call.
type EditorService_discardRecovery_Params_Future struct{ *capnp.Future }

func (f EditorService_discardRecovery_Params_Future) Struct() (EditorService_discardRecovery_Params, error) {
	p, err := f.Future.Ptr()
	return EditorService_discardRecovery_Params(p.Struct()), err
}

type EditorService_discardRecovery_Results capnp.Struct

// EditorService_discardRecovery_Results_TypeID is the unique identifier for the type EditorService_discardRecovery_Results.
const EditorService_discardRecovery_Results_TypeID = 0x88464e707e21dab3

func NewEditorService_discardRecovery_Results(s *capnp.Segment) (EditorService_discardRecovery_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EditorService_discardRecovery_Results(st), err
}

func NewRootEditorService_discardRecovery_Results(s *capnp.Segment) (EditorService_discardRecovery_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EditorService_discardRecovery_Results(st), err
}

func ReadRootEditorService_discardRecovery_Results(msg *capnp.Message) (EditorService_discardRecovery_Results, error) {
	root, err := msg.Root()
	return EditorService_discardRecovery_Results(root.Struct()), err
}

func (s EditorService_discardRecovery_Results) String() string {
	str, _ := text.Marshal(0x88464e707e21dab3, capnp.Struct(s))
	return str
}

func (s EditorService_discardRecovery_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditorService_discardRecovery_Results) DecodeFromPtr(p capnp.Ptr) EditorService_discardRecovery_Results {
	return EditorService_discardRecovery_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditorService_discardRecovery_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditorService_discardRecovery_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditorService_discardRecovery_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditorService_discardRecovery_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditorService_discardRecovery_Results) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditorService_discardRecovery_Results) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditorService_discardRecovery_Results) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditorService_discardRecovery_Results) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// EditorService_discardRecovery_Results_List is a list of EditorService_discardRecovery_Results.
type EditorService_discardRecovery_Results_List = capnp.StructList[EditorService_discardRecovery_Results]

// NewEditorService_discardRecovery_Results creates a new list of EditorService_discardRecovery_Results.
func NewEditorService_discardRecovery_Results_List(s *capnp.Segment, sz int32) (EditorService_discardRecovery_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EditorService_discardRecovery_Results](l), err
}

// EditorService_discardRecovery_Results_Future is a wrapper for a EditorService_discardRecovery_Results promised by a client call.
type EditorService_discardRecovery_Results_Future struct{ *capnp.Future }

func (f EditorService_discardRecovery_Results_Future) Struct() (EditorService_discardRecovery_Results, error) {
	p, err := f.Future.Ptr()
	return EditorService_discardRecovery_Results(p.Struct()), err
}

type EditOp capnp.Struct

// EditOp_TypeID is the unique identifier for the type EditOp.
const EditOp_TypeID = 0x9204a190c081b3a5

func NewEditOp(s *capnp.Segment) (EditOp, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1})
	return EditOp(st), err
}

func NewRootEditOp(s *capnp.Segment) (EditOp, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1})
	return EditOp(st), err
}

func ReadRootEditOp(msg *capnp.Message) (EditOp, error) {
	root, err := msg.Root()
	return EditOp(root.Struct()), err
}

func (s EditOp) String() string {
	str, _ := text.Marshal(0x9204a190c081b3a5, capnp.Struct(s))
	return str
}

func (s EditOp) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EditOp) DecodeFromPtr(p capnp.Ptr) EditOp {
	return EditOp(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EditOp) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EditOp) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EditOp) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EditOp) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EditOp) ClientId() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s EditOp) SetClientId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s EditOp) Version() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s EditOp) SetVersion(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s EditOp) Type() EditOp_OpType {
	return EditOp_OpType(capnp.Struct(s).Uint16(16))
}

func (s EditOp) SetType(v EditOp_OpType) {
	capnp.Struct(s).SetUint16(16, uint16(v))
}

func (s EditOp) InsertLine() uint32 {
	return capnp.Struct(s).Uint32(20)
}

func (s EditOp) SetInsertLine(v uint32) {
	capnp.Struct(s).SetUint32(20, v)
}

func (s EditOp) InsertCol() uint32 {
	return capnp.Struct(s).Uint32(24)
}

func (s EditOp) SetInsertCol(v uint32) {
	capnp.Struct(s).SetUint32(24, v)
}

func (s EditOp) InsertText() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EditOp) HasInsertText() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EditOp) InsertTextBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EditOp) SetInsertText(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EditOp) FromLine() uint32 {
	return capnp.Struct(s).Uint32(28)
}

func (s EditOp) SetFromLine(v uint32) {
	capnp.Struct(s).SetUint32(28, v)
}

func (s EditOp) FromCol() uint32 {
	return capnp.Struct(s).Uint32(32)
}

func (s EditOp) SetFromCol(v uint32) {
	capnp.Struct(s).SetUint32(32, v)
}

func (s EditOp) ToLine() uint32 {
	return capnp.Struct(s).Uint32(36)
}

func (s EditOp) SetToLine(v uint32) {
	capnp.Struct(s).SetUint32(36, v)
}

func (s EditOp) ToCol() uint32 {
	return capnp.Struct(s).Uint32(40)
}

func (s EditOp) SetToCol(v uint32) {
	capnp.Struct(s).SetUint32(40, v)
}

// EditOp_List is a list of EditOp.
type EditOp_List = capnp.StructList[EditOp]

// NewEditOp creates a new list of EditOp.
func NewEditOp_List(s *capnp.Segment, sz int32) (EditOp_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 48, PointerCount: 1}, sz)
	return capnp.StructList[EditOp](l), err
}

// EditOp_Future is a wrapper for a EditOp promised by a client call.
type EditOp_Future struct{ *capnp.Future }

func (f EditOp_Future) Struct() (EditOp, error) {
	p, err := f.Future.Ptr()
	return EditOp(p.Struct()), err
}

type EditOp_OpType uint16

// EditOp_OpType_TypeID is the unique identifier for the type EditOp_OpType.
const EditOp_OpType_TypeID = 0xce808f7bfdbadb18

// Values of EditOp_OpType.
const (
	EditOp_OpType_noop   EditOp_OpType = 0
	EditOp_OpType_insert EditOp_OpType = 1
	EditOp_OpType_delete EditOp_OpType = 2
)

// String returns the enum's constant name.
func (c EditOp_OpType) String() string {
	switch c {
	case EditOp_OpType_noop:
		return "noop"
	case EditOp_OpType_insert:
		return "insert"
	case EditOp_OpType_delete:
		return "delete"

	default:
		return ""
	}
}

// EditOp_OpTypeFromString returns the enum value with a name,
// or the zero value if there's no such value.
func EditOp_OpTypeFromString(c string) EditOp_OpType {
	switch c {
	case "noop":
		return EditOp_OpType_noop
	case "insert":
		return EditOp_OpType_insert
	case "delete":
		return EditOp_OpType_delete

	default:
		return 0
	}
}

type EditOp_OpType_List = capnp.EnumList[EditOp_OpType]

func NewEditOp_OpType_List(s *capnp.Segment, sz int32) (EditOp_OpType_List, error) {
	return capnp.NewEnumList[EditOp_OpType](s, sz)
}

const schema_d75b3b54eb3ed6a2 = "x\xda\xc4Vol\x14[\x15?\xe7\xde\xd9\xce\xeef" +
	"\xf7m\xc7Y\xf2\x0a\xcf\xa6\xef\xcf\x1a\xdb\xf2h\xe8k" +
	"\xcd\xeb\xeb\xe3\xb9\xdb\x16\x9e>\x02vo\xb7\x18AH" +
	"Xvoeq\xbb3\xeeN\xab\xf5\x0f\xa5(\x09\x98" +
	" \x7f\xa2F4\x8a6b\x8cF\x10\x10M\x88\x1a\xf1" +
	"\x83\x01\x124\x10\xa3\xa1\xca\x07\xa3\x06\x0dJ$\x18C" +
	"?\x941gvgv(\x0b\xb6_|\x1f\xe77\xe7" +
	"\x9e\xfb;\xe7\xfc\xce\xb9g\xedf%\xa5tGO\x06" +
	"\x81\x89|\xa0\xc9\xde\xff\xd1\xde\x1f\x1e\xfe\xf7\xa1}\xa0" +
	"=\x87\x00\x8a\x0a\xd0\xf3\x1ee\x10A\xb1\xf7\xce\xee\xb9" +
	"\xfb\xd2\x99\xf9\x19\x10\xcf!\x03\x08 \xfdkUF\x10" +
	"P\xefP\xce\x00\xda\xe7\xe7^\xd8k~\xe0\xcd\x83\xd5" +
	"\xb3U\x83+\xcaW\xc9\xe0\xa6\x92\x04\xb4O\x9d\x9f\xf9" +
	"\xc5\xd1o)\xc7AD\xb1\xc9\x9e\xfd\xdd{\xef\x8c\xbe" +
	"\xfe\xe1\xdfW-\xf5yeV\xc7\xc0\xb3\x00=\xa1\xc0" +
	"\xab\x0c\xd0~\xf1k\x1dS;~4\xf3\x95G.\xdc" +
	"\xaa\xee\"\x7fR\xbd\x0dh\x7f\xf6\xe4\x9a\x99\xebM\xbf" +
	"=]\xb3p\xd8\x0e\x04\x8f\x93\x81\x08~\x1c\xd0>\xf6" +
	"\xd2\xf4\xe1\xaf\x7f\xf3\xf2y2\xe05\x83\x0b\xc1=d" +
	"p)H\x94/\x9f\xbex\xe3a\xff\x97\x7f\xea\x0bW" +
	"\x86>I\xe1^\xb8\xba}\xd5\xea\xff\xfc\xeb\xe7t\xd4" +
	"\xfd%B\xdb\xe8\xe8\x8e\x10\x05\xf3\x9d\xbb\xf2\xee\xc0w" +
	"\x07\xaf\xfa/\xffL\xa8L\x06\x87Bt\xf9\x9ao," +
	"\xdc\x1bJ\x8d_\xaby\xa8\xf2\xffg\xd5\xc5\xbcc\x91" +
	"\xfd\xe2\x03\\\xb5\xf0\x8fk\xfe;\xb6\x86\xbfG\x06\x85" +
	"0\xdd\xd1\xf2\x87\x8b\x0b\x9f:\xb2\xef\xd7\xa0\xc5Y=" +
	"{tCxN\xffR\x98\xd2v,<\x0ch\xe3I" +
	"\xe3h\xcf\xbd\x99\x1b\xa0Ey=\xb1\x80\xfa\xa9\xf0\x9c" +
	"~\x96\x0c{~\x10~\x1f\xd3\xbb#*\x80}\xf4a" +
	"\xe5O\x97\x16V\xfe\xf1\x11f+#\x0e\xf7wE\x88" +
	"\xd9\xea\x83}7\xdf\xf1\xf9go\xf9\x83;\x16\xe9'" +
	"\x83\x13\x8e\xc1\xb9D\xeb\x81\xf6C\x03\x7f\xf1%n!" +
	"2B\x89\xdb=\xf7\x85\xfb\xb7\x7f\xf2\xfd\xbf\xf9\x83\xfa" +
	"{d\xd6\x89:BA\xddyk\xe07\xbfZ\xfd\xb9" +
	"\xfb\xbe\xa3\xad\xd12\x1d\xc5_~\xfb\xf5w\xff\xf9\xd5" +
	"\x07\xfe\xa3\xa1\xa8\x93\xb0\x15Q:j\x9fk>\xd2\xf5" +
	"\xe3\xd3\x0b~\x83\xd7\xa2N=7D\x93\xb0\xc6\x96\xf9" +
	"\x82e\x94\xbbr\xa1\xacY2\xfb78_\x19Y\x9e" +
	",\xe4dW%;)\x13#\xb22Q\xb4*\xe0\x1a" +
	"6\xb0\xcb\x9afqj\xd8L\xa4\xb3\xe5\xec8VD" +
	"\x84+\x00\x0a\x02h\x1b6\x02\x88\xf5\x1cE\x9a\xa1\x86" +
	",N\x1c\xb4\xcd\x04n\xe2(>\xc4\x900\x06\xa0m" +
	"Y\x05 \xd2\x1c\xc5v\x86v\xaeX\x90%\xeb\xad<" +
	"\x00`\x08\x18\x86\x00\xed]\x13cc\xb2\\\xc5\x82\xc0" +
	"0\x08\xc8\x0d\x13\x9b\xfdE\xc6f@/\xa0@\x03\xa2" +
	"\xf9B%\x97-\xe7Gd\xce\x98\x94\xe5\xa9jl\xdc" +
	"\xaa\x08\xc5c\x1c\x1d\x04\x10A\x8e\"\xcep:g\x94" +
	",Y\xb20\x02\x0c#>\xdf\xe8\xfaV\xadaS(" +
	"\xe8\xd7\x1d\xf6'\x87\xcd\xd1)S\x8av\xd7\xa9\x1e\xc2" +
	"\x8d\x00\x99 r\xcc\xc4\x912\x81N&t\x0d\x07\x01" +
	"2\x11\xc2[\x08gA'\x1b\xfa\x0a\xec\x04\xc84\x13" +
	"\xfeN\xc2y N\xdd\xa8\xaf\xc4m\x00\x99\x16\xc2\x13" +
	"\x84+MqT\x00\xf4\x17p\x04 \xf3<\xe1/#" +
	"C\x0c\xc41\x00\xa0w8\xe6\xed\x04\xf7\x92y\x93\x1a" +
	"\xc7&\x00\xbd\xdb\xa1\xb3\x96\xf0u\x84\xab\xc1\xb83P" +
	"^s\xe8\xf4\x12\x9e\"<\x18\x8ac\x10@\x7f\x03\xfb" +
	"\x012}\x84\xaf'<\x14\x8ec\x08@\x1f\xc0W\x00" +
	"2\xeb\x08\x7f?6\xae\xdb\xf4\xa4,W\x0aF\xc9\xfd" +
	"\x8eYS\xa6\xc4X=_\x80\x18\x03\xb4\x0b\xa5\x8a," +
	"[\x9b\x0a\xc0K\xd2\xado\x0d\x1c2\x00\x8b\x8b\xb0Q" +
	"\x09\xfc\x13\xf5\xba\x8c\x95\x8d\xf1M\x85\x92\xf4\x89c\x9a" +
	"\xb0!\xc3;\x98\xb4\x0c\xb2p?\xdb,\xc3\xf7\xd3+" +
	"\xac\xd2@4\x86)Ko\x16\x8a\xd5NP\x8bVE" +
	"4{j\xc9\x92\x94wr\x14E\x86\xb5\xa2j\x05R" +
	"P\x9e\xa30\xa9\xa2X\xd5\xf78\x81\xbb9\x0a\x8b\xca" +
	"\xf9\xbcSN\xedc{\x00\x84\xc9Q|\x9a5\x14\xf8" +
	"b\xfd-N\xa6\x137\x89\x19b$gD`\x88\xcb" +
	"l\x01\xb7g\x83^L\x1d\x14S;G\xd1\xeb\xeb\xd9" +
	"n\x02\xd7r\x14\xeb\x96\xde\x9fO\xcd\xeaG\xa4\xb5\xc5" +
	"\xccg-YI\xa4\xb3\xb1rv|YcCc\xee" +
	"\xdc\xa0\x14\x8er\x14;\x97\xc1\xabR(\xe5\xe4\x07e" +
	"\x19b\x8fd\xf3itsE\xa3\"\x07\x1d_\x89\x91" +
	"du$>\xf5\x80;\x13\xff\xd7\x88Y\\\xd2\xa5\x92" +
	"H\xb7e\x9d\xa4\xfd\xbf\xeb\xe6u\x03\x09\x87?\x91\x80" +
	"\xdb\x0c\xdd\x9d\x00\xe2e\x8e\xa2\xaf\xf1\xfd13k\xed" +
	"~l\xbe6\x12n\x95\xe8\x90\xe3b\xc8\x98(Y\x94" +
	"\xda\x18\xd5\xc1\x9f\xdaW\xea\xa9m\xcb\x91\xd5cA1" +
	"\xcf\xf7\xb0\xd9E\x93\x9a\x9b2\x8d(\"\x8e\x9eZ;" +
	"i\"i+\xfa\x01\x90i\xd1~\x80X\xc90\xccd" +
	"u\xec$\xf3\xb2(-\xd9\xc0W\x8d'\xcf9\xbe\x12" +
	"<\x00\xe0\xbd\xf8\xe8\xbe\xd2\xce\xbcgz\x00U\xac\xbf" +
	"\xcc\xe8\xbe\xee\xda\xfc6`\xda=\x15\x99\xb7\x08\xa1\xbb" +
	"\xd1i\x7f\xdd\x08L\xbb\xa5\"\xf764tw\x12\xed" +
	":\x9d\xbb\xa2b}\xe3Dw\x17\xd3~6\x08L;" +
	"\xabb\xc0[P\xd0]X\xb5S\x9d\xc0\xb4\x13*6" +
	"y\x9b\x19\xba\xdb\x9dvx\x170\xed\x80\x8a\xaa\xb7\x9d" +
	"\xa0\xbb{iS\xc7\x81i\x13*\x06\xbdu\x12\xddE" +
	"V+\xec\x07\xa6eU\x9a\\%\x99\xb3Rh\xd3\xc0" +
	"\xa1\x0f\xe0\xce\xa7\xab\x1f\x00H\xa1\xedN\x01\xe0\xb2\x92" +
	"\xc2\xe9Z\xd3\xa40F\xabG\x8a\x14SU<\xa8c" +
	"\xb2\x9cr\xd5:TDW\x05\xe8^A3\x0dkC" +
	"\x0dR\x98\xc6%\x8f\x9f\x11\xd9\xe6\xb4\xb3_\xc9/\x02" +
	"\x88\x04G\x91\xaa+\xf9\x0d\xea\xda>\x8eb=C\xd5" +
	"0+\xf8\x0c`\x9a\xe3\xa2\x0d\xe4\x19xrK\xf3'" +
	"\xadX\xc9\xf4\xdb\xd3\xcb\xb5\"\xb9o\xc02\xdb/\x9d" +
	"-\xab\xc4\xda\xd7}D0\xc2Q\xb4\xb0\xe5\x93qu" +
	"\x92\xb3\xbc\x8a,\x89|\xa3\x01\xeb\xe7\xd1(QK\xe4" +
	"\xe1>LK\xf7\xfc\xdf\x00\x00\x00\xff\xffG\xe5\xac3"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d75b3b54eb3ed6a2,
		Nodes: []uint64{
			0x8089f48db0346b82,
			0x81f9af23ee6aa27e,
			0x88464e707e21dab3,
			0x9204a190c081b3a5,
			0x9881b45d79299b22,
			0xaed406d1812d9f83,
			0xb3c8a09d8d7f2391,
			0xbc963afed2baaec8,
			0xbef0f62b1a5ccab5,
			0xca42a841ee65eea6,
			0xcd6d4043f1fd9e2d,
			0xcdecfd1a01f89461,
			0xce808f7bfdbadb18,
			0xd281f133906f9f01,
			0xdc19fdc1e173fe90,
			0xdd178a12d938882b,
			0xe4418928851d24b2,
			0xe8abb7e7f38eda68,
			0xf3842bc6cf4149eb,
			0xf837e3273ba4c201,
			0xfdaeb62e8f10b2ff,
		},
		Compressed: true,
	})
}
