package client

import (
	"fmt"
	"sort"
	"strings"
)

// DumpKeybindsTOML returns a commented-out [[keybind]] TOML skeleton
// listing every built-in action, grouped by category, generated from the
// same source the help popup reads (help_gen.go) — so it can't drift the
// way a hand-written reference doc would as actions get added. Exported
// for cmd/indigo's --dump-keybinds flag.
//
// Deliberately covers built-in actions only, not plugin actions: plugins
// are per-workspace/per-plugin-set and configured through each plugin's
// own trigger_key in its plugin.toml manifest, not this global config
// file — a global dump can't meaningfully enumerate them. See the live "?"
// help popup for currently-registered plugin bindings instead.
func DumpKeybindsTOML() string {
	var b strings.Builder
	b.WriteString("# Available actions for [[keybind]] overrides.\n")
	b.WriteString("# Generated by `indigo --dump-keybinds` from indigo's built-in keymap —\n")
	b.WriteString("# do not hand-edit this file; re-run to regenerate after upgrading indigo.\n")
	b.WriteString("# Uncomment a block and adjust `key` to rebind it; mode is \"normal\" or\n")
	b.WriteString("# \"insert\". Plugin actions aren't listed here — see the \"?\" help popup.\n\n")

	writeRow := func(mode string, row *treeHelpRow) {
		// The comment shows the full key sequence (e.g. "miw" for a
		// Match-submenu leaf) so it's unambiguous which action this is; the
		// actual key = "..." placeholder below uses just the leaf's own key
		// (row.rawKeys[0]) since that's what a [[keybind]] override actually
		// needs — a single key, not a multi-press sequence.
		fmt.Fprintf(&b, "# %s — default key: %s\n", row.label, strings.Join(row.seqs, " / "))
		b.WriteString("# [[keybind]]\n")
		fmt.Fprintf(&b, "# mode = %q\n", mode)
		fmt.Fprintf(&b, "# key = %q\n", row.rawKeys[0])
		fmt.Fprintf(&b, "# action = %q\n\n", row.name)
	}

	byCategory := map[string][]*treeHelpRow{}
	for _, row := range collectHelpRows(defaultPrefixCmds) {
		byCategory[row.category] = append(byCategory[row.category], row)
	}
	for _, cat := range orderedCategories(byCategory) {
		fmt.Fprintf(&b, "# --- %s (normal mode) ---\n", cat)
		for _, row := range byCategory[cat] {
			writeRow("normal", row)
		}
	}

	// Insert mode is a small, flat list with no per-action categorization —
	// matches generateHelpEntries' treatment of it in the help popup.
	if insertRows := collectHelpRows(defaultInsertCmds); len(insertRows) > 0 {
		b.WriteString("# --- Insert mode ---\n")
		for _, row := range insertRows {
			writeRow("insert", row)
		}
	}

	b.WriteString("# --- No default key (bind one to use it as a keypress) ---\n")
	names := make([]string, 0, len(exOnlyActions))
	for name := range exOnlyActions {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "# %s\n", exOnlyDisplay[name].label)
		b.WriteString("# [[keybind]]\n")
		b.WriteString("# mode = \"normal\"\n")
		b.WriteString("# key = \"\"\n")
		fmt.Fprintf(&b, "# action = %q\n\n", name)
	}

	return b.String()
}
